//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWIFIPHOTORES_H
#define UIFLOWWNDWIFIPHOTORES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_MAP_BEGIN(UIFlowWndWiFiPhoto)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndWiFiPhoto)
DECLARE_CTRL_LIST(UIFlowWndWiFiPhoto)
CREATE_CTRL(UIFlowWndWiFiPhoto,UIFlowWndWiFiPhoto,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
