//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWIFIPLAYBACK_H
#define UIFLOWWNDWIFIPLAYBACK_H

#include "UIFramework.h"

extern VControl UIFlowWndWiFiPlaybackCtrl;//Panel type 

//---------------------UIFlowWndWiFiPlaybackCtrl User Export---------------------------
#endif
