//This source code is generated by UI Designer Studio.
#ifdef __ECOS
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndWiFiMovieRes.c"
#include "UIFlowWndWiFiMovie.h"
#include "SysCommon.h"
#include "AppCommon.h"
#include "PrjCfg.h"
#include "WifiAppCmd.h"
#include "UIMovieObj.h"
#include "UIAppMovie.h"
#include "MovieInterface.h"
#include "UIFlowMovieFuncs.h"
#include "md_api.h"
#include "MovieInterface.h"
#include "UIFlowMovieIcons.h"

//---------------------UIFlowWndWiFiMovieCtrl Debug Definition -----------------------------
#define _UIFLOWWNDWIFIMOVIE_ERROR_MSG        1
#define _UIFLOWWNDWIFIMOVIE_TRACE_MSG        0

#if (_UIFLOWWNDWIFIMOVIE_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndWiFiMovieErrMsg(...)            debug_msg ("^R UIFlowWndWiFiMovie: "__VA_ARGS__)
#else
#define UIFlowWndWiFiMovieErrMsg(...)
#endif

#if (_UIFLOWWNDWIFIMOVIE_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndWiFiMovieTraceMsg(...)          debug_msg ("^B UIFlowWndWiFiMovie: "__VA_ARGS__)
#else
#define UIFlowWndWiFiMovieTraceMsg(...)
#endif

//---------------------UIFlowWndWiFiMovieCtrl Global Variables -----------------------------
//static BOOL    g_UIWiFiMovRecMotionDet = FALSE;

//---------------------UIFlowWndWiFiMovieCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndWiFiMovieCtrl Public API  ----------------------------------

//---------------------UIFlowWndWiFiMovieCtrl Private API  ---------------------------------

void FlowWiFiMovie_StartRec(UINT32 type)
{
#if(MOVIE_LIVEVIEW==RTSP_LIVEVIEW)
    UI_SetData(FL_WIFI_MOVIE_FMT,type);
    Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_START, 0);
    Ux_SendEvent(&UIMovieRecObjCtrl, NVTEVT_START_RTSP, 0);

#else //((MOVIE_LIVEVIEW==HTTP_LIVEVIEW) ||(MOVIE_LIVEVIEW==DUAL_REC_HTTP_LIVEVIEW))
    UI_SetData(FL_WIFI_MOVIE_FMT,type);
    if(type ==WIFI_RTSP_REC)
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_START, 0);
    else
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_STOP, 0);

    //Ux_SendEvent(&UIMovieRecObjCtrl, NVTEVT_START_RTSP, 0);
#endif
}

void FlowWiFiMovie_StopRec(void)
{
#if(MOVIE_LIVEVIEW==RTSP_LIVEVIEW)
    Ux_SendEvent(&UIMovieRecObjCtrl, NVTEVT_STOP_RTSP, 0);
    Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_STOP, 0);

#else //((MOVIE_LIVEVIEW==HTTP_LIVEVIEW) ||(MOVIE_LIVEVIEW==DUAL_REC_HTTP_LIVEVIEW))
    //Ux_SendEvent(&UIMovieRecObjCtrl, NVTEVT_STOP_RTSP, 0);
    //Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_STOP, 0);
#endif
}

//---------------------UIFlowWndWiFiMovieCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndWiFiMovie)
CTRL_LIST_END

//----------------------UIFlowWndWiFiMovieCtrl Event---------------------------
INT32 UIFlowWndWiFiMovie_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWiFiMovie_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWiFiMovie_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWiFiMovie_OnExeMovieRec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWiFiMovie_OnExeSetMovieSize(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWiFiMovie_OnExeMovieTriggerRawEnc(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndWiFiMovie)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndWiFiMovie_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndWiFiMovie_OnClose)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndWiFiMovie_OnTimer)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_REC,UIFlowWndWiFiMovie_OnExeMovieRec)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_REC_SIZE,UIFlowWndWiFiMovie_OnExeSetMovieRecSize)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_TRIGGER_RAWENC, UIFlowWndWiFiMovie_OnExeMovieTriggerRawEnc)
EVENT_END

INT32 UIFlowWndWiFiMovie_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;
    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    {
    case NVTEVT_05SEC_TIMER:
        // Motion Detect function
        if (SysGetFlag(FL_MOVIE_MOTION_DET) == MOVIE_MOTIONDET_ON && System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)
        {
            static UINT32  uiMotionDetGo = 0;
            static UINT32  uiMotionDetStop = 0;

            if (MD_Process()==TRUE)
            {
                 uiMotionDetGo++;
                 if (uiMotionDetGo>=2)
                 {
                    uiMotionDetStop=0;
                    if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_LVIEW)
                    {
                        debug_msg("^GStart Record\r\n");
                        // reset uiMotionDetGo
                        uiMotionDetGo = 0;
                        //#NT#2016/12/30#Isiah Chang -begin
                        // Send socket to notify APP movie recording is started.
                        // Post event to record video and send socket to notify APP recording is started.
                        Ux_PostEvent(NVTEVT_WIFI_EXE_MOVIE_REC, 1, 1);
                        //#NT#2016/12/30#Isiah Chang -end
                    }
                 }
            }
            else
            {
                uiMotionDetStop++;
                if (uiMotionDetStop>=2) // 1 sec
                {
                    uiMotionDetGo=0;
                }
                #if 1
                if (uiMotionDetStop>=20) // 10 Sec
                #else
                if (uiMotionDetStop>=65536) // 10 Sec
                #endif
                {
                    uiMotionDetStop = 0;
                    if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_RECORD)
                    {
                        if (FlowMovie_GetRecCurrTime() >= 1 || (SysGetFlag(FL_MOVIE_TIMELAPSE_REC) != MOVIE_TIMELAPSEREC_OFF))
                        {
                            #if 0
                            FlowWiFiMovie_StopRec();
                            FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);
                            if ( FALSE == AE_Wait_Stable(3, 60) )
                                debug_msg("Motion Detection: AE do not stable\r\n");
                            #endif
                            debug_msg("^RWIFIAPP_RET_RECORD_STOPPED\r\n");
                            //#NT#2016/12/30#Isiah Chang -begin
                            // Send socket to notify APP movie recording is started.
                            #if 0
                            WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STOPPED);
                            #else
                            // Post event to record video and send socket to notify APP recording is started.
                            Ux_PostEvent(NVTEVT_WIFI_EXE_MOVIE_REC, 1, 0);
                            #endif
                            //#NT#2016/12/30#Isiah Chang -end
                        }
                        break;
                    }
                }
            }
        }

        break;
    }

    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnExeMovieRec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    BOOL startRec =0;
    UINT32 uiNotifyAPPStatus = 0;
    UINT32 result = WIFIAPP_RET_OK;
    UINT32 curStatus = 0;
    if(paramNum>0)
    {
        startRec=paramArray[0];

        if(paramNum > 1)
        {
            uiNotifyAPPStatus = paramArray[1];
        }
    }

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        WifiCmd_Done(WIFIFLAG_RECORD_DONE,WIFIAPP_RET_STATE_ERR);
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    curStatus = UIFlowWndWiFiMovie_GetStatus();

    if(startRec)
    {
        if (curStatus == WIFI_MOV_ST_LVIEW)
        {
            UINT32 MaxTime = UIFlowWiFiMovie_GetMaxRecTime();

            if((MaxTime<=2) && (SysGetFlag(FL_MOVIE_CYCLIC_REC) == MOVIE_CYCLICREC_OFF))
            {
                result = WIFIAPP_RET_STORAGE_FULL;
                UIFlowWndWiFiMovieErrMsg("recTime<2 sec\r\n");
            }
            else
            {
                // Reset Current record time
                FlowMovie_SetRecCurrTime(0);

                //#NT#2016/12/30#Isiah Chang -begin
                // Send socket to notify APP movie recording is started.
                #if 0
                // Send socket to notify APP movie recording is started.
                if(uiNotifyAPPStatus)
                {
                    WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STARTED);
                }
                else
                #endif
                {
                    FlowWiFiMovie_StopRec();
                    FlowWiFiMovie_StartRec(WIFI_RTSP_REC);
                }
                //#NT#2016/12/30#Isiah Chang -end
            }
        }
        else if(curStatus == WIFI_MOV_ST_IDLE)
        {
            result = WIFIAPP_RET_FAIL;
            UIFlowWndWiFiMovieErrMsg("idle state,cannot record\r\n");
        }
    }
    else  //stop rec
    {
        UINT32 recordTime = FlowMovie_GetRecCurrTime();
        if ((curStatus == WIFI_MOV_ST_RECORD) && ((recordTime >= 1) || (SysGetFlag(FL_MOVIE_TIMELAPSE_REC) != MOVIE_TIMELAPSEREC_OFF)))
        {
            FlowWiFiMovie_StopRec();
            FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);
            // Notify Maximum Record Time
            UI_SetData(FL_WIFI_MOVIE_MAXRECTIME, UIMovRecObj_GetData(RECMOVIE_MAXSECOND));
        }
        else if ((curStatus == WIFI_MOV_ST_RECORD) &&(recordTime < 1))
        {
            result = WIFIAPP_RET_FAIL;
            UIFlowWndWiFiMovieErrMsg("recTime<1 sec %d sts %d\r\n",recordTime,UIFlowWndWiFiMovie_GetStatus());
        }
        else if(curStatus == WIFI_MOV_ST_IDLE)
        {
            result = WIFIAPP_RET_FAIL;
            UIFlowWndWiFiMovieErrMsg("idle state,cannot stop\r\n");
        }
    }
    // Notify Done

    //#NT#2016/12/30#Isiah Chang -begin
    // Send socket to notify APP movie recording is started.
    if(SysGetFlag(FL_MOVIE_MOTION_DET) == MOVIE_MOTIONDET_ON)
    {
        Delay_DelayMs(1000);
        if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_RECORD)
        {
            WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STARTED);
        }
        else
        {
            WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_RECORD_STOPPED);
        }
    }
    //#NT#2016/12/30#Isiah Chang -end

    WifiCmd_Done(WIFIFLAG_RECORD_DONE,result);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieRecSize(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
#if ((MOVIE_LIVEVIEW==HTTP_LIVEVIEW) ||(MOVIE_LIVEVIEW==DUAL_REC_HTTP_LIVEVIEW))
        PhotoExe_CloseHttpLiveView();
#endif
        Ux_SendEvent(&CustomMovieObjCtrl,NVTEVT_EXE_MOVIESIZE, 1, Data);
        UI_SetData(FL_MOVIE_SIZE, Data); // Update FL_MOVIE_SIZE meanwhile.
        Ux_SendEvent(&CustomMovieObjCtrl,NVTEVT_EXE_IMAGE_RATIO, 1, Data);
#if ((MOVIE_LIVEVIEW==HTTP_LIVEVIEW) ||(MOVIE_LIVEVIEW==DUAL_REC_HTTP_LIVEVIEW))
        PhotoExe_OpenHttpLiveView();
#endif
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetCyclicRec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        Ux_SendEvent(&CustomMovieObjCtrl,NVTEVT_EXE_CYCLIC_REC, 1, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetHDR(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_HDR, 1, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieEV(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_EV, 1, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMotionDet(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOTION_DET, 1, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieAudio(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_AUDIO, 1, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieDateImprint(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_DATE_IMPRINT, 1, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieLiveviewSize(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        UI_SetData(FL_WIFI_MOVIE_APP_PREVIEW_SIZE, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieGSesnorSensitivity(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_GSENSOR, 1, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetAutoRecording(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 Data;

    Data = paramNum ? paramArray[0] : 0;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
    {
        UI_SetData(FL_WIFI_AUTO_RECORDING, Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieRecBitRate(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    char *Data = 0;
    UINT32 uiTargetBitRate;


    if(paramNum)
    {
        Data = (char *)paramArray[0];

        if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
        {
            UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
            WifiCmd_UnlockString(Data);
            return NVTEVT_CONSUME;
        }

        if (1 == sscanf(Data, "%d", &uiTargetBitRate))
        {
            if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
            {
                debug_msg("Rec target bit rate:%d KBytes\r\n", uiTargetBitRate);
                SetMovieTargetBitrate(1, UI_GetData(FL_MOVIE_SIZE), uiTargetBitRate * 1024);
            }
        }
        WifiCmd_UnlockString(Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeSetMovieLiveviewBitRate(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    char *Data = 0;
    UINT32 uiTargetBitRate;

    if(paramNum)
    {
        Data = (char *)paramArray[0];

        if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
        {
            UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
            WifiCmd_UnlockString(Data);
            return NVTEVT_CONSUME;
        }

        if (1 == sscanf(Data, "%d", &uiTargetBitRate))
        {
            if (UIFlowWndWiFiMovie_GetStatus() != WIFI_MOV_ST_RECORD)
            {
                debug_msg("Preview target bit rate:%d KBytes\r\n", uiTargetBitRate);
                SetMovieTargetBitrate(0, UI_GetData(FL_WIFI_MOVIE_APP_PREVIEW_SIZE), uiTargetBitRate * 1024);
            }
        }
        WifiCmd_UnlockString(Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeMovieLiveviewStart(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    BOOL startLview =0;
    UINT32 result = WIFIAPP_RET_OK;
    UINT32 curStatus = 0;
    if(paramNum>0)
    {
        startLview = paramArray[0];
    }

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        WifiCmd_Done(WIFIFLAG_PREVIEW_DONE, WIFIAPP_RET_STATE_ERR);
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    curStatus = UIFlowWndWiFiMovie_GetStatus();
    if(startLview)
    {
        if(curStatus==WIFI_MOV_ST_IDLE)
        {
            FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);
        }
        else if(curStatus==WIFI_MOV_ST_RECORD)
        {
            result = WIFIAPP_RET_FAIL;
            UIFlowWndWiFiMovieErrMsg("recording\r\n");
        }

    }
    else
    {
        if(curStatus==WIFI_MOV_ST_LVIEW)
        {
            FlowWiFiMovie_StopRec();
        }
        else if(curStatus==WIFI_MOV_ST_RECORD)
        {
            result = WIFIAPP_RET_FAIL;
            UIFlowWndWiFiMovieErrMsg("recording\r\n");
        }
    }

    WifiCmd_Done(WIFIFLAG_PREVIEW_DONE,result); // signal wi-fi app cmd is done.
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnExeMovieTriggerRawEnc(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 result = WIFIAPP_RET_OK;
    UINT32 curStatus = 0;
    UINT32 uiJpegWidth, uiJpegHeight, uiDAR, uiMovieSize;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        WifiCmd_Done(WIFIFLAG_PREVIEW_DONE, WIFIAPP_RET_STATE_ERR);
        UIFlowWndWiFiMovieErrMsg("not movie mode\r\n");
        return NVTEVT_CONSUME;
    }

    curStatus = UIFlowWndWiFiMovie_GetStatus();
    if(curStatus == WIFI_MOV_ST_RECORD)
    {
        uiMovieSize = UI_GetData(FL_MOVIE_SIZE);
        uiJpegWidth = GetMovieSizeWidth(uiMovieSize);
        uiJpegHeight = GetMovieSizeHeight(uiMovieSize);
        uiDAR = GetMovieDispAspectRatio(uiMovieSize);
        if (uiDAR == VIDENC_DAR_16_9)
        {
            uiJpegWidth = (uiJpegHeight * 16) / 9;
        }

        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_RAWENC, 2, uiJpegWidth, uiJpegHeight);
    }
    else
    {
        result = WIFIAPP_RET_FAIL;
        UIFlowWndWiFiMovieErrMsg("Not in recording state\r\n");

        WifiCmd_Done(WIFIFLAG_MOVIE_REC_RAWENC_DONE, result); // signal wi-fi app cmd is done.
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIFlowWndWiFiMovieErrMsg("%s \r\n",__FUNCTION__);
    WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS,WIFIAPP_RET_MOVIE_FULL);

    //moive is stopped by media record library;project need to stop RTSP
    Ux_SendEvent(&UIMovieRecObjCtrl, NVTEVT_STOP_RTSP, 0);
    FlowMovie_SetRecCurrTime(0);
    FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIFlowWndWiFiMovieErrMsg("%s \r\n",__FUNCTION__);

    // Something wrong with card. Mark file system error status.
    UI_SetData(FL_FSStatus, FS_DISK_ERROR);
    WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS,WIFIAPP_RET_MOVIE_WR_ERROR);

    //moive is stopped by media record library;project need to stop RTSP
    Ux_SendEvent(&UIMovieRecObjCtrl, NVTEVT_STOP_RTSP, 0);
    FlowMovie_SetRecCurrTime(0);
    FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnStorageSlow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIFlowWndWiFiMovieErrMsg("%s \r\n",__FUNCTION__);
    WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS,WIFIAPP_RET_MOVIE_SLOW);

    //moive is stopped by media record library;project need to stop RTSP
    #if 0
    Ux_SendEvent(&UIMovieRecObjCtrl, NVTEVT_STOP_RTSP, 0);
    FlowMovie_SetRecCurrTime(0);
    FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);
    #else // Restart recording automatically when slow card event occurred.
    FlowMovie_SetRecCurrTime(0);
    FlowWiFiMovie_StopRec();
    FlowWiFiMovie_StartRec(WIFI_RTSP_REC);
    #endif

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnDeleteFiles(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //debug_msg("Delete Files!\r\n");
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnDeleteROFiles(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //debug_msg("Delete RO Files!\r\n");
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWiFiMovie_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (UIFlowWndWiFiMovie_GetStatus()==WIFI_MOV_ST_RECORD && paramNum)
    {
        FlowMovie_SetRecCurrTime(paramArray[0]);
		FlowMovie_IconDrawRecTime(&UIMenuWndWiFiMobileLinkOK_Static_timeCtrl);
		if(UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl)){
			FlowMovie_IconHideRec(&UIMenuWndWiFiMobileLinkOK_PanelCtrl);
		}
		else{
			FlowMovie_IconDrawRec(&UIMenuWndWiFiMobileLinkOK_PanelCtrl);
		}		
        //WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_MOVIETIME,paramArray[0]);
    }
	FlowWifiMovie_IconDrawDateTime();
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnMovieRawEncJpgOKCB(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 result = WIFIAPP_RET_OK;

    WifiCmd_Done(WIFIFLAG_MOVIE_REC_RAWENC_DONE, result); // signal wi-fi app cmd is done.

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_OnMovieRawEncErr(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 result = WIFIAPP_RET_FAIL;

    CHKPNT;
    WifiCmd_Done(WIFIFLAG_MOVIE_REC_RAWENC_DONE, result); // signal wi-fi app cmd is done.

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndWiFiMovie_GetStatus(void)
{
    UINT32 status;

#if(MOVIE_LIVEVIEW==RTSP_LIVEVIEW)
    if(MovRec_IsRecording()==TRUE && UI_GetData(FL_WIFI_MOVIE_FMT)==WIFI_RTSP_LIVEVIEW)
        status = WIFI_MOV_ST_LVIEW;
    else if(MovRec_IsRecording()==TRUE && UI_GetData(FL_WIFI_MOVIE_FMT)==WIFI_RTSP_REC)
        status = WIFI_MOV_ST_RECORD;
    else
        status = WIFI_MOV_ST_IDLE;

#else //((MOVIE_LIVEVIEW==HTTP_LIVEVIEW) ||(MOVIE_LIVEVIEW==DUAL_REC_HTTP_LIVEVIEW))
    if(MovRec_IsRecording()==TRUE)
        status = WIFI_MOV_ST_RECORD;
    else
        status = WIFI_MOV_ST_LVIEW;

#endif
    return status;
}


UINT32 UIFlowWiFiMovie_GetMaxRecTime(void)
{
    MEDIAREC_CALCSEC_SETTING setting;
    UINT32 sec;

    setting.nowFSFreeSpace = FileSys_GetDiskInfo(FST_INFO_FREE_SPACE);
    setting.vidfps = GetMovieFrameRate(UI_GetData(FL_MOVIE_SIZE));//30;
    setting.vidTBR = GetMovieTargetBitrate(UI_GetData(FL_MOVIE_SIZE), 0);//0x180000;
    setting.audSampleRate = 32000;
    setting.audCodec = MOVAUDENC_PCM;
    setting.audChs = 1;
    setting.clustersize = FileSys_GetDiskInfo(FST_INFO_CLUSTER_SIZE);
    setting.gpson = 1;
    setting.nidxon= 1;

    //UIFlowWndWiFiMovieTraceMsg("fps %d vidTBR %d sampleRate  %d chNum %d\r\n",setting.vidfps,setting.vidTBR,setting.audSampleRate,setting.audChs);
    if(!setting.nowFSFreeSpace || !setting.clustersize)
    {
        debug_msg("No free space\r\n");
        return 0;
    }
    else
    {
        sec = MovRec_CalcSecBySetting(&setting);
    }
    //UIFlowWndWiFiMovieTraceMsg("sec = %d \r\n", sec);
    return sec ;
}

#endif
