//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWIFIPHOTO_H
#define UIFLOWWNDWIFIPHOTO_H

#include "UIFramework.h"

extern VControl UIFlowWndWiFiPhotoCtrl;//Panel type

//---------------------UIFlowWndWiFiPhotoCtrl User Export---------------------------
extern INT32 UIFlowWndWiFiPhoto_OnExePhotoCapture(VControl *, UINT32, UINT32 *);
extern INT32 UIFlowWndWiFiPhoto_OnUpdateInfo(VControl *, UINT32, UINT32 *);
extern INT32 UIFlowWndWiFiPhoto_OnExeSetPhotoSize(VControl *, UINT32, UINT32 *);

#endif
