
#----------------------------------------------------------------------
# set the library name here
#----------------------------------------------------------------------
PRJ_NAME = IPL_NT99231_EVB_FF

#----------------------------------------------------------------------
# add/delete source files here
#----------------------------------------------------------------------
SRC = \
	IPL_Cmd_NT99231_EVB_FF.c \
	IPL_Mode_NT99231_EVB_FF.c \
	IPL_Isr_NT99231_EVB_FF.c \
	IPL_Buf_NT99231_EVB_FF.c \
	IPL_dzoomTab_NT99231_EVB_FF.c \
	IPL_Ctrl_NT99231_EVB_FF.c \
	IPL_CtrlNormal_NT99231_EVB_FF.c \
	IPL_CtrlFWPProc_NT99231_EVB_FF.c \
	IPL_CtrlFW_NT99231_EVB_FF.c \
	IPL_D2DCB_NT99231_EVB_FF.c \
	IPL_FlowCB_NT99231_EVB_FF.c \
    IQS_SettingFlow_NT99231_EVB_FF.c \
    IQS_SettingTable_NT99231_EVB_FF.c \
    IQS_ImageEffectTable_NT99231_EVB_FF.c

ASM =

#----------------------------------------------------------------------
# set the include directory here
#----------------------------------------------------------------------
INC_DIR = . \
	../../../../Include \
	../../../../Lib/Lib_src/DevCam/IPL_COMMON \

#----------------------------------------------------------------------
# set the image output directory here
#----------------------------------------------------------------------
IMG_BASE_DIR = ../../../../ARC/Lib

#----------------------------------------------------------------------
# add additional C and assembly flags here
#----------------------------------------------------------------------
CFLAGS_D =
ASMFLAGS_D =

CFLAGS_R =
ASMFLAGS_R =

#----------------------------------------------------------------------
# include common parts of the makefile
#----------------------------------------------------------------------
MAKE_COMMON_DIR = ../../../../MakeCommon
include $(MAKE_COMMON_DIR)/OutputLib.txt
