//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDCALIBRATION_H
#define UIMENUWNDCALIBRATION_H

#include "UIFramework.h"

extern VControl UIMenuWndCalibrationCtrl;//Panel type 

extern VControl UIMenuWndCalibration_BackgroundCtrl;//Panel type 

extern VControl UIMenuWndCalibration_TitleBarCtrl;//Panel type 

extern VControl UIMenuWndCalibration_TitleNameCtrl;//Static type 

extern VControl UIMenuWndCalibration_TipsBarCtrl;//Panel type 

extern VControl UIMenuWndCalibration_UDOKTipsCtrl;//Panel type 

extern VControl UIMenuWndCalibration_ItemCtrl;//Menu type 

typedef enum
{
UIMenuWndCalibration_Item_STRID_A1,
UIMenuWndCalibration_Item_STRID_A2,
UIMenuWndCalibration_Item_STRID_A3,
UIMenuWndCalibration_Item_STRID_A4,
UIMenuWndCalibration_Item_MAX
}UIMenuWndCalibration_Item_Setting;

#endif
