//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "GPSTestWndRes.c"
#include "GPSTestWnd.h"
#include "PrjCfg.h"
#include "GxTimer.h"
#include "UIFlow.h"
#include "Sensor.h"
#include "DxSensor.h"
#include "GPS.h"

#define MSG_X_GAP       60
#define MSG_Y_GAP       40

#define VX1_TITLE_X     12
#define VX1_TITLE_Y     112
#define VX1_DATA_X      (VX1_TITLE_X + MSG_X_GAP)
#define VX1_DATA_Y      VX1_TITLE_Y

#define GPS_TITLE_X     VX1_TITLE_X
#define GPS_TITLE_Y     (VX1_TITLE_Y + MSG_Y_GAP)
#define GPS_DATA_X      VX1_DATA_X
#define GPS_DATA_Y      GPS_TITLE_Y

#define OBD_TITLE_X     VX1_TITLE_X
#define OBD_TITLE_Y     (GPS_TITLE_Y + MSG_Y_GAP)
#define OBD_DATA_X      VX1_DATA_X
#define OBD_DATA_Y      OBD_TITLE_Y

//---------------------GPSTestWndCtrl Debug Definition -----------------------------
#define _GPSTESTWND_ERROR_MSG        1
#define _GPSTESTWND_TRACE_MSG        0

#if (_GPSTESTWND_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define GPSTestWndErrMsg(...)            debug_msg ("^R GPSTestWnd: "__VA_ARGS__)
#else
#define GPSTestWndErrMsg(...)
#endif

#if (_GPSTESTWND_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define GPSTestWndTraceMsg(...)          debug_msg ("^B GPSTestWnd: "__VA_ARGS__)
#else
#define GPSTestWndTraceMsg(...)
#endif

//---------------------GPSTestWndCtrl Global Variables -----------------------------
static BOOL     g_bGPSTestWndOpen = FALSE;
static UINT32   g_uiGPSTestTimer = NULL_TIMER;
static RMCINFO  g_RMCInfo;

//---------------------GPSTestWndCtrl Prototype Declaration  -----------------------

//---------------------GPSTestWndCtrl Public API  ----------------------------------

//---------------------GPSTestWndCtrl Private API  ---------------------------------
static void GPSTestWnd_CheckGPSData(void)
{
    CHAR    cDataStr[32];
    static BOOL bGPSDetected = FALSE;

    if (g_bGPSTestWndOpen)
    {
        memset((void *)cDataStr, 0, sizeof(cDataStr));

        if (GPSRec_GetRMCDate(&g_RMCInfo) == TRUE)
        {
            bGPSDetected = TRUE;
            snprintf(cDataStr, sizeof(cDataStr), "%04d/%02d/%02d %02d:%02d:%02d",\
                (int)g_RMCInfo.Year, (int)g_RMCInfo.Month, (int)g_RMCInfo.Day, (int)g_RMCInfo.Hour, (int)g_RMCInfo.Minute, (int)g_RMCInfo.Second);
            UI_DrawOsdString(cDataStr, GPS_DATA_X, GPS_DATA_Y, CLRID_IDX_GREEN, TRUE);
        }
        else
        {
            if (bGPSDetected == FALSE)
            {
                snprintf(cDataStr, sizeof(cDataStr), "No Data                 ");
                UI_DrawOsdString(cDataStr, GPS_DATA_X, GPS_DATA_Y, CLRID_IDX_RED, TRUE);
            }
        }
    }
}

static void GPSTestWnd_CheckOBDData(void)
{
    CHAR    cDataStr[32];
    static BOOL bOBDDetected = FALSE;

    if (g_bGPSTestWndOpen)
    {
        memset((void *)cDataStr, 0, sizeof(cDataStr));

        if (0) // TO DO: need to check and get OBD data here
        {
            bOBDDetected = TRUE;
            // TO DO: show OBD message here
        }
        else
        {
            if (bOBDDetected == FALSE)
            {
                snprintf(cDataStr, sizeof(cDataStr), "No Data                 ");
                UI_DrawOsdString(cDataStr, OBD_DATA_X, OBD_DATA_Y, CLRID_IDX_RED, TRUE);
            }
        }
    }
}

//---------------------GPSTestWndCtrl Control List---------------------------
CTRL_LIST_BEGIN(GPSTestWnd)
CTRL_LIST_END

//----------------------GPSTestWndCtrl Event---------------------------
INT32 GPSTestWnd_OnOpen(VControl *, UINT32, UINT32 *);
INT32 GPSTestWnd_OnClose(VControl *, UINT32, UINT32 *);
INT32 GPSTestWnd_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(GPSTestWnd)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,GPSTestWnd_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,GPSTestWnd_OnClose)
EVENT_ITEM(NVTEVT_TIMER,GPSTestWnd_OnTimer)
EVENT_END

INT32 GPSTestWnd_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_bGPSTestWndOpen = TRUE;
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    Ux_Redraw();

    UI_DrawOsdString("Vx1: ", VX1_TITLE_X, VX1_TITLE_Y, CLRID_IDX_BLUE, FALSE);
    UI_DrawOsdString("GPS: ", GPS_TITLE_X, GPS_TITLE_Y, CLRID_IDX_BLUE, FALSE);
    UI_DrawOsdString("OBD: ", OBD_TITLE_X, OBD_TITLE_Y, CLRID_IDX_BLUE, FALSE);

    #if 0
    if (DrvSensor_DetPlugIn(SENSOR_ID_2))
        UI_DrawOsdString("ON",  VX1_DATA_X, VX1_DATA_Y, CLRID_IDX_GREEN, FALSE);
    else
        UI_DrawOsdString("OFF", VX1_DATA_X, VX1_DATA_Y, CLRID_IDX_RED, FALSE);
    #endif

    GPSTestWnd_CheckGPSData();
    GPSTestWnd_CheckOBDData();

    if (g_uiGPSTestTimer == NULL_TIMER)
    {
        g_uiGPSTestTimer = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
    }

    return NVTEVT_CONSUME;
}
INT32 GPSTestWnd_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_uiGPSTestTimer != NULL_TIMER)
    {
        GxTimer_StopTimer(&g_uiGPSTestTimer);
    }

    g_bGPSTestWndOpen = FALSE;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 GPSTestWnd_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;

    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    {
    case NVTEVT_1SEC_TIMER:
        GPSTestWnd_CheckGPSData();
        GPSTestWnd_CheckOBDData();
        break;
    }

    return NVTEVT_CONSUME;
}

