//This source code is generated by UI Designer Studio.

#ifndef GPSTESTWND_H
#define GPSTESTWND_H

#include "UIFramework.h"

extern VControl GPSTestWndCtrl;//Panel type 

//---------------------GPSTestWndCtrl User Export---------------------------
#endif
