//This source code is generated by UI Designer Studio.

#ifndef GPSTESTWNDRES_H
#define GPSTESTWNDRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Skin1Rect,0,0,319,239,0,0,0,0,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_MAP_BEGIN(GPSTestWnd)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(GPSTestWnd)
DECLARE_CTRL_LIST(GPSTestWnd)
CREATE_CTRL(GPSTestWnd,GPSTestWnd,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
