//This source code is generated by UI Designer Studio.

#ifndef WAVTESTWND_H
#define WAVTESTWND_H

#include "UIFramework.h"

extern VControl WavTestWndCtrl;//Panel type 

//---------------------WavTestWndCtrl User Export---------------------------
#endif
