//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONITEM_H
#define MENUCOMMONITEM_H

#include "UIFramework.h"

extern VControl MenuCommonItemCtrl;//Panel type 

extern VControl MenuCommonItem_BGCtrl;//Panel type 

extern VControl MenuCommonItem_TitleBarCtrl;//Panel type 

extern VControl MenuCommonItem_TitleIconTab1Ctrl;//Static type 

extern VControl MenuCommonItem_TitleIconTab2Ctrl;//Static type 

extern VControl MenuCommonItem_TitleTextCtrl;//Static type 

extern VControl MenuCommonItem_TipsBarCtrl;//Panel type 

extern VControl MenuCommonItem_TipsIconReturnCtrl;//Static type 

extern VControl MenuCommonItem_TipsIconLDRCtrl;//Panel type 

extern VControl MenuCommonItem_TipsIconLUDRCtrl;//Panel type 

extern VControl MenuCommonItem_TipsIconLUDOKCtrl;//Panel type 

extern VControl MenuCommonItem_PageNumCtrl;//Static type 

extern VControl MenuCommonItem_MenuCtrl;//Menu type 

typedef enum
{
MenuCommonItem_Menu_STRID_A0,
MenuCommonItem_Menu_STRID_A1,
MenuCommonItem_Menu_STRID_A2,
MenuCommonItem_Menu_STRID_A3,
MenuCommonItem_Menu_STRID_A4,
MenuCommonItem_Menu_STRID_A5,
MenuCommonItem_Menu_STRID_A6,
MenuCommonItem_Menu_STRID_A7,
MenuCommonItem_Menu_STRID_A8,
MenuCommonItem_Menu_STRID_A9,
MenuCommonItem_Menu_STRID_B0,
MenuCommonItem_Menu_STRID_B1,
MenuCommonItem_Menu_STRID_B2,
MenuCommonItem_Menu_STRID_B3,
MenuCommonItem_Menu_STRID_B4,
MenuCommonItem_Menu_STRID_B5,
MenuCommonItem_Menu_STRID_B6,
MenuCommonItem_Menu_STRID_B7,
MenuCommonItem_Menu_STRID_B8,
MenuCommonItem_Menu_STRID_B9,
MenuCommonItem_Menu_MAX
}MenuCommonItem_Menu_Setting;

extern VControl MenuCommonItem_TabBarCtrl;//Panel type 

//---------------------MenuCommonItemCtrl User Export---------------------------
#endif
