//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONOPTION_H
#define MENUCOMMONOPTION_H

#include "UIFramework.h"

extern VControl MenuCommonOptionCtrl;//Panel type 

extern VControl MenuCommonOption_PanelCtrl;//Panel type 

extern VControl MenuCommonOption_MenuCtrl;//Menu type 

typedef enum
{
MenuCommonOption_Menu_STRID_A0,
MenuCommonOption_Menu_STRID_A1,
MenuCommonOption_Menu_STRID_A2,
MenuCommonOption_Menu_STRID_A3,
MenuCommonOption_Menu_STRID_A4,
MenuCommonOption_Menu_STRID_A5,
MenuCommonOption_Menu_STRID_A6,
MenuCommonOption_Menu_STRID_A7,
MenuCommonOption_Menu_STRID_A8,
MenuCommonOption_Menu_STRID_A9,
MenuCommonOption_Menu_STRID_B0,
MenuCommonOption_Menu_STRID_B1,
MenuCommonOption_Menu_STRID_B2,
MenuCommonOption_Menu_STRID_B3,
MenuCommonOption_Menu_STRID_B4,
MenuCommonOption_Menu_STRID_B5,
MenuCommonOption_Menu_STRID_B6,
MenuCommonOption_Menu_STRID_B7,
MenuCommonOption_Menu_STRID_B8,
MenuCommonOption_Menu_STRID_B9,
MenuCommonOption_Menu_MAX
}MenuCommonOption_Menu_Setting;

//---------------------MenuCommonOptionCtrl User Export---------------------------
#endif
