//This source code is generated by UI Designer Studio.

////////////////////////////////////////////////////////////////////////////////
#include "SysCommon.h"
#include "AppCommon.h"
#include "UICommon.h"
////////////////////////////////////////////////////////////////////////////////
#include "UIPlayComm.h"
#include "FlowCommon.h"
#include "UIStorageCheck.h"

#include "FileSysTsk.h"
#include "DispSrvApi.h"
#include "GxDisplay.h"
#include "Dx.h"
#include "DxType.h"

#define _UIPLAYCOMM_ERROR_MSG        1
#define _UIPLAYCOMM_TRACE_MSG        0

#if (_UIPLAYCOMM_ERROR_MSG && (PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIPlayCommErrMsg(...)            debug_msg ("^R UIPlayComm: "__VA_ARGS__)
#else
#define UIPlayCommErrMsg(...)
#endif

#if (_UIPLAYCOMM_TRACE_MSG && (PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIPlayCommTraceMsg(...)          debug_msg ("^B UIPlayComm: "__VA_ARGS__)
#else
#define UIPlayCommTraceMsg(...)
#endif

extern DX_HANDLE gDevLCDObj;
extern DX_HANDLE gDevTVObj;
extern DX_HANDLE gDevHDMIObj;

#define AUTO_HIDE_TIME  2000//ms
URECT g_ThumbRectVideoComm[MAX_THUMB_RECT_NUM] = {0};
//#NT#2012/11/27#Scottie -begin
//#NT#Support Dual Display for PB
URECT g_ThumbRectVideoComm2[MAX_THUMB_RECT_NUM] = {0};
//#NT#2012/11/27#Scottie -end
extern COORDTS_HANDLE g_hTsOsdToVdo;

static UINT32 g_uiAutoHideID = NULL_TIMER;
//#NT#2011/01/31#Ben Wang -begin
//#NT#Add screen control to sync display with OSD
static UINT32 g_uiStartX = 0;
static UINT32 g_uiStartY = 0;
static UINT32 g_uiWidth = TOOL_LAYOUT_W;
static UINT32 g_uiHeight = TOOL_LAYOUT_H;
//#NT#2011/01/31#Ben Wang -end
//#NT#2011/03/30#Ben Wang -begin
//#NT#Add common key sound setting
static UINT32 g_uiPressKeySound = FLGKEY_SOUND_MASK_DEFAULT | FLGKEY_ZOOMIN | FLGKEY_ZOOMOUT;
static UINT32 g_uiContKeySound = FLGKEY_SOUND_MASK_DEFAULT;
//#NT#2011/03/30#Ben Wang -end
void CloseAutoHideTimer()
{
    //#NT#2011/03/14#Ben Wang -begin
    //#NT#Use CONTINUE timer instead.
    //g_uiAutoHideID = NULL_TIMER;
    StopAutoHideTimer();
    //#NT#2011/03/14#Ben Wang -end
}
void StopAutoHideTimer()
{
    if(g_uiAutoHideID != NULL_TIMER)
        GxTimer_StopTimer(&g_uiAutoHideID);
}
void ResetAutoHideTimer()
{
    StopAutoHideTimer();
    //#NT#2011/03/14#Ben Wang -begin
    //#NT#Use CONTINUE timer instead.
    //g_uiAutoHideID = GxTimer_StartTimer(AUTO_HIDE_TIME, NVTEVT_SELFTIMER, ONE_SHOT);
    g_uiAutoHideID = GxTimer_StartTimer(AUTO_HIDE_TIME, NVTEVT_SELFTIMER, CONTINUE);
    //#NT#2011/03/14#Ben Wang -end
}
void ResetPlayKeySound(void)
{
    Input_SetKeySoundMask(KEY_PRESS, FLGKEY_SOUND_MASK_DEFAULT | FLGKEY_ZOOMIN | FLGKEY_ZOOMOUT);
    Input_SetKeySoundMask(KEY_CONTINUE, FLGKEY_SOUND_MASK_DEFAULT);
}
//#NT#2011/03/30#Ben Wang -begin
//#NT#Add common key sound setting
void UIWndBackupKeySound(void)
{
    g_uiPressKeySound = Input_GetKeySoundMask(KEY_PRESS);
    g_uiContKeySound = Input_GetKeySoundMask(KEY_CONTINUE);
}
void UIWndRestoreKeySound(void)
{
    Input_SetKeySoundMask(KEY_PRESS, g_uiPressKeySound);
    Input_SetKeySoundMask(KEY_CONTINUE, g_uiContKeySound);
}
void UIWndSetActiveKeySound(UINT32 uiPressKeySound, UINT32 uiContKeySound)
{
    Input_SetKeySoundMask(KEY_PRESS, uiPressKeySound);
    Input_SetKeySoundMask(KEY_CONTINUE, uiContKeySound);
}
//#NT#2011/03/30#Ben Wang -end
void ChkKeySoundComm(void)
{
    UINT32 uiDefaultSound = Input_GetKeySoundMask(KEY_PRESS);

    if(AppPlay_GetData(PLAY_FILENUM) <= 1)
        uiDefaultSound &= ~(FLGKEY_LEFT| FLGKEY_RIGHT);
    else
        uiDefaultSound |= (FLGKEY_LEFT| FLGKEY_RIGHT);

    Input_SetKeySoundMask(KEY_PRESS, uiDefaultSound);
    Input_SetKeySoundMask(KEY_CONTINUE, uiDefaultSound);
}
void PlayNextPhotoComm(void)
{
    SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, FALSE);
    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_NEXT, 1);
    SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, TRUE);
}
void PlayPrevPhotoComm(void)
{
    SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, FALSE);
    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_PREV, 1);
    SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, TRUE);
}
BOOL IsFreeSpaceEnough(void)
{
    UINT64 freeSpece = 0;
    freeSpece = FileSys_GetDiskInfo(FST_INFO_FREE_SPACE);
    if(AppPlay_GetData(PLAY_FILESIZE) < freeSpece)
        return TRUE;
    else
        return FALSE;
}
BOOL IsFileError(void)
{
    UINT32 uiStatus;
    uiStatus = AppPlay_GetData(PLAY_PBSTATUS);
    if(uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE))
        return TRUE;
    else
        return FALSE;
}
BOOL IsMovieFile(void)
{
    UINT32 uiCurrMode = AppPlay_GetData(PLAY_CURRMODE);
    if(uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG)
        return TRUE;
    else
        return FALSE;
}
BOOL IsNoJpgFile(void)
{
    UINT32 JPGNum = 0;

    JPGNum = AppPlay_GetData(PLAY_FILENUM);
    if(JPGNum == 0)
        return TRUE;
    else
        return FALSE;
}
BOOL IsPanoramaImg(void)
{
    #if 0
    if(EXIF_NOT_EXIST == AppPlay_GetData(PLAY_EXIF_SPEC_FUN))
    {
        return FALSE;
    }
    else if((AppPlay_GetData(PLAY_EXIF_SPEC_FUN)&0x0F) == 0x03)
    {// This is one panorama image..
        return TRUE;
    }
    else
    #endif
    {
        return FALSE;
    }
}
BOOL IsHDRImg(void)
{
    #if 0
    if(EXIF_NOT_EXIST == AppPlay_GetData(PLAY_EXIF_SPEC_FUN))
    {
        return FALSE;
    }
    else if(AppPlay_GetData(PLAY_EXIF_SPEC_FUN)&0xF0)
    {
        return TRUE;
    }
    else
    #endif
    {
        return FALSE;
    }
}
BOOL IsOurImg(void)
{
    #if 0
    if(EXIF_NOT_EXIST == AppPlay_GetData(PLAY_EXIF_CERTIFICATION))
    {
        return FALSE;
    }
    else if(AppPlay_GetData(PLAY_EXIF_CERTIFICATION))
    {
        return TRUE;
    }
    else
    {
        return FALSE;
    }
    else
    #endif
        return TRUE;
}
BOOL IsHDMIPlugIn(void)
{
    DX_HANDLE DevObj1, DevObj2;
    DevObj1 = (DX_HANDLE)GxVideo_GetDevice(DOUT1);
    DevObj2 = (DX_HANDLE)GxVideo_GetDevice(DOUT2);
    if(DevObj1 == gDevHDMIObj || DevObj2 == gDevHDMIObj)
        return TRUE;
    else
        return FALSE;
}
BOOL ExceedMaxPlayByDateFileNum(void)
{
    if(AppPlay_GetData(PLAY_FILENUM) > MAX_PLAY_BY_DATE_FILE_NUM)
        return TRUE;
    else
        return FALSE;
}
//#NT#2010/11/23#Ben Wang -begin
//#NT#Refine code for browse window
void BrowseThumbUpdateLayout(URECT* pOSDRect, UINT32 uiThumbNum)
{
    DISPSRV_CMD DispCmd={0};
    DISPSRV_DISP_CFG CfgDisp={0};
    COORDTS_TARGET Target={0};
    COORDTS_TRANS  Trans={0};

    //wait DispSrv finish setting
    memset(&DispCmd,0,sizeof(DISPSRV_CMD));
    DispCmd.Idx = DISPSRV_CMD_IDX_GET_DISP;
    DispCmd.Prop.bExitCmdFinish = TRUE;
    DispCmd.Out.uiNumByte = sizeof(CfgDisp);
    DispCmd.Out.pData= &CfgDisp;
    DispSrv_Cmd(&DispCmd);

    Target.hHandle = g_hTsOsdToVdo;
    Target.SizeTarget.w = CfgDisp.Desc[DISPSRV_DISP_IDX_PRIMARY].pDisp[0].Width;
    Target.SizeTarget.h = CfgDisp.Desc[DISPSRV_DISP_IDX_PRIMARY].pDisp[0].Height;
    Target.pRcRegion = NULL;
    CoordTs_SetTarget(&Target);

    Trans.hHandle = g_hTsOsdToVdo;
    Trans.bInverse = FALSE;
    Trans.Method = COORDTS_METHOD_FULL_FIT;
    Trans.pRcSrc = pOSDRect;
    Trans.pRcDst = g_ThumbRectVideoComm;
    Trans.uiRectNum = uiThumbNum;
    CoordTs_TransRect(&Trans);

//#NT#2012/11/27#Scottie -begin
//#NT#Support Dual Display for PB
    if(TRUE == CfgDisp.bDual)
    {
        Target.hHandle = g_hTsOsdToVdo;
        Target.SizeTarget.w = CfgDisp.Desc[DISPSRV_DISP_IDX_SECONDARY].pDisp[0].Width;
        Target.SizeTarget.h = CfgDisp.Desc[DISPSRV_DISP_IDX_SECONDARY].pDisp[0].Height;
        Target.pRcRegion = NULL;
        CoordTs_SetTarget(&Target);

        Trans.hHandle = g_hTsOsdToVdo;
        Trans.bInverse = FALSE;
        Trans.Method = COORDTS_METHOD_FULL_FIT;
        Trans.pRcSrc = pOSDRect;
        Trans.pRcDst = g_ThumbRectVideoComm2;
        Trans.uiRectNum = uiThumbNum;
        CoordTs_TransRect(&Trans);
    }
//#NT#2012/11/27#Scottie -end
}

void BrowseThumbNaviKey(PBROWSE_NAVI_INFO pBrowseNavi)
{
    UINT32  CurrFileIndex;
    UINT32  CurrFileSeqID, FileNumsInDir;
    UINT32  FileNumsInFinalPage, FileNumsInFinalLine;
    UINT16  *pThumbSeqID;
    UINT32  CurThumbNums, CurrPageID, FinalPageID;
    UINT32  NumsPerPage, CurrThumbRow, FinalThumbRow, NextFileIndex;
    UINT32  BrowserCommand = 0, JumpOffset = 0;


    CurrFileIndex = AppPlay_GetData(PLAY_BROWSEINDEX);
    pThumbSeqID = (UINT16 *)AppPlay_GetData(PLAY_ALLTHUMBSEQ);
    pThumbSeqID += (CurrFileIndex-1);
    CurrFileSeqID = *pThumbSeqID;
    NumsPerPage = pBrowseNavi->HorNums*pBrowseNavi->VerNums;

    FileNumsInDir = AppPlay_GetData(PLAY_FILENUM);

    if(FileNumsInDir == 0)
        return;

    if((FileNumsInDir % NumsPerPage) == 0)
        FileNumsInFinalPage = NumsPerPage;
    else
        FileNumsInFinalPage = FileNumsInDir % NumsPerPage;

    if((FileNumsInFinalPage % pBrowseNavi->HorNums) == 0)
        FileNumsInFinalLine = pBrowseNavi->HorNums;
    else
        FileNumsInFinalLine = FileNumsInFinalPage % pBrowseNavi->HorNums;

    CurrPageID  = ((CurrFileSeqID-1) / NumsPerPage);
    FinalPageID = ((FileNumsInDir-1) / NumsPerPage);

    CurThumbNums = AppPlay_GetData(PLAY_CURRTHUMBNUM);

    CurrThumbRow  = (CurrFileIndex-1)/pBrowseNavi->HorNums;
    FinalThumbRow = (CurThumbNums-1)/pBrowseNavi->HorNums;

    UIPlayCommTraceMsg("key=0x%x, CurrFileIndex=%d, CurrFileSeqID=%d\r\n",pBrowseNavi->NaviKey, CurrFileIndex,CurrFileSeqID);
    UIPlayCommTraceMsg("NumsPerPage=%d, FileNumsInDir=%d\r\n",NumsPerPage, FileNumsInDir);
    UIPlayCommTraceMsg("FileNumsInFinalPage=%d, FileNumsInFinalLine=%d\r\n",FileNumsInFinalPage, FileNumsInFinalLine);
    UIPlayCommTraceMsg("CurrPageID=%d, FinalPageID=%d\r\n",CurrPageID, FinalPageID);
    UIPlayCommTraceMsg("CurThumbNums=%d, CurrThumbRow=%d, FinalThumbRow=%d\r\n",CurThumbNums, CurrThumbRow,FinalThumbRow);

    // page-direction (LEFT)
    if(pBrowseNavi->NaviKey == NVTEVT_KEY_LEFT)
    {
        BrowserCommand = PB_BROWSER_PREV;
        JumpOffset     = 1;
    }
    // page-direction (RIGHT)
    else if(pBrowseNavi->NaviKey == NVTEVT_KEY_RIGHT)
    {
        BrowserCommand = PB_BROWSER_NEXT;
        JumpOffset     = 1;
    }
    // page-direction (UP)
    else if(pBrowseNavi->NaviKey == NVTEVT_KEY_UP)
    {
        BrowserCommand = PB_BROWSER_PREV;

        if(CurrPageID > 0)
        {// means now is not 1st-page, decode the same file-index-image
            JumpOffset = pBrowseNavi->HorNums;
        }
        else // if(CurrPageID == 0)
        {// means now is 1st-page
            if(CurrThumbRow > 0)
            {// means CurrThumbRow=1,2, do not change page, decode the same file-index-image
                JumpOffset = pBrowseNavi->HorNums;
            }
            else if(FileNumsInDir <= NumsPerPage)
            {// means only one page & CurrThumbRow = 0,

                if(FinalThumbRow == 0)
                {// means only one row, do nothing
                    JumpOffset = 0;
                }
                else if(FileNumsInFinalLine >= CurrFileIndex)
                {// must decode the same file-index-image
                    JumpOffset = FileNumsInFinalLine;
                }
                else
                {// must decode the same file-index-image
                    JumpOffset = pBrowseNavi->HorNums + FileNumsInFinalLine;
                }
            }
            else
            {// means CurrThumbRow=0, go to final page
                if(FileNumsInFinalPage < pBrowseNavi->HorNums)
                {// means final-page file nums < 3 (only one line),
                    if(FileNumsInFinalLine >= CurrFileIndex)
                    {// must decode the same file-index-image
                        JumpOffset = FileNumsInFinalLine;
                    }
                    else
                    {// must decode final file-index-image
                        JumpOffset = CurrFileIndex;
                    }
                }
                else
                {// means final-page file nums >= 3
                    if(FileNumsInFinalLine >= CurrFileIndex)
                    {// must decode the same file-index-image
                        JumpOffset = FileNumsInFinalLine;
                    }
                    else
                    {// must decode the same file-index-image
                        JumpOffset = pBrowseNavi->HorNums + FileNumsInFinalLine;
                    }
                }
            }
        }// else if(CurrPageID == 0)
    }
    // page-direction (DOWN)
    else if(pBrowseNavi->NaviKey & NVTEVT_KEY_DOWN)
    {
        BrowserCommand = PB_BROWSER_NEXT;

        if((CurrPageID+1) < FinalPageID)
        {// means now is not final-page & (final-1)-page, decode the same file-index-image
            JumpOffset = pBrowseNavi->HorNums;
        }
        else if((CurrPageID+1) == FinalPageID)
        {// means now is (final-1)-page, go to final-page
            if(CurrThumbRow != FinalThumbRow)
            {// means CurrThumbRow != MaxRow, do not change page, decode the same file-index-image
                JumpOffset = pBrowseNavi->HorNums;
            }
            else if(FileNumsInFinalPage < pBrowseNavi->HorNums)
            {// means final-page file nums < 3 (only one line),
                if((CurrFileIndex % pBrowseNavi->HorNums) == 0)
                {
                    NextFileIndex = pBrowseNavi->HorNums;
                }
                else
                {
                    NextFileIndex = CurrFileIndex % pBrowseNavi->HorNums;
                }

                if(FileNumsInFinalLine >= NextFileIndex)
                {// must decode the same file-index-image
                    JumpOffset = pBrowseNavi->HorNums;
                }
                else
                {// must decode final file-index-image
                    JumpOffset = pBrowseNavi->HorNums - (NextFileIndex - FileNumsInFinalLine);
                }
            }
            else
            {// must decode the same file-index-image
                JumpOffset = pBrowseNavi->HorNums;
            }
        }
        else // if(CurrPageID == FinalPageID)
        {// means now is final-page
            if( (CurrFileIndex + pBrowseNavi->HorNums) <= CurThumbNums)
            {// means do not change page, decode the same file-index-image
                JumpOffset = pBrowseNavi->HorNums;
            }
            else if(FileNumsInDir <= NumsPerPage)
            {// means only one page & CurrThumbRow=end,
                if(FinalThumbRow == 0)
                {   // means only one row, do nothing
                    JumpOffset = 0;
                }
                else if(CurrThumbRow != FinalThumbRow)
                {
                    JumpOffset = (pBrowseNavi->HorNums + FileNumsInFinalLine);
                }
                else
                {
                    JumpOffset = (FileNumsInFinalLine);
                }
            }
            else
            {// means now is final-page, go to 1st-page
             // must decode the same file-index-image
                if(CurrThumbRow != FinalThumbRow)
                {
                    JumpOffset = (pBrowseNavi->HorNums + FileNumsInFinalLine);
                }
                else
                {
                    JumpOffset = (FileNumsInFinalLine);
                }
            }
        }// End of if(CurrPageID == FinalPageID)
    }
    else
    {
        UIPlayCommErrMsg("Only support navigation key\r\n");
    }
    UIPlayCommTraceMsg("BrowserCommand=0x%x, JumpOffset=%d\r\n",BrowserCommand, JumpOffset);
    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_BROWSESINGLE, 2, BrowserCommand, JumpOffset);
}
//#NT#2010/11/23#Ben Wang -end
//#NT#2011/01/31#Ben Wang -begin
//#NT#Add screen control to sync display with OSD
void SetVdoWinSizeForPB(UINT32 uiStartX, UINT32 uiStartY, UINT32 uiWidth, UINT32 uiHeight)
{
    g_uiStartX = uiStartX;
    g_uiStartY = uiStartY;
    g_uiWidth = uiWidth;
    g_uiHeight = uiHeight;
    UI_Show(UI_SHOW_PLAYBACK, TRUE);
}
void UpdateVdoWinForPB(void)
{
    URECT rcSrc, rcDst;
    COORDTS_TRANS  Trans={0};
    COORDTS_TARGET Target={0};
    DISPSRV_CMD DispCmd={0};
    DISPSRV_DISP_CFG CfgDisp={0};

    //wait DispSrv finish setting
    memset(&DispCmd,0,sizeof(DISPSRV_CMD));
    DispCmd.Idx = DISPSRV_CMD_IDX_GET_DISP;
    DispCmd.Prop.bExitCmdFinish = TRUE;
    DispCmd.Out.uiNumByte = sizeof(CfgDisp);
    DispCmd.Out.pData= &CfgDisp;
    DispSrv_Cmd(&DispCmd);

    Target.hHandle=g_hTsOsdToVdo;
    Target.SizeTarget.w = CfgDisp.Desc[DISPSRV_DISP_IDX_PRIMARY].pDisp[0].Width;
    Target.SizeTarget.h = CfgDisp.Desc[DISPSRV_DISP_IDX_PRIMARY].pDisp[0].Height;
    Target.pRcRegion = NULL;
    CoordTs_SetTarget(&Target);

    rcSrc.x = g_uiStartX;
    rcSrc.y = g_uiStartY;
    rcSrc.w = g_uiWidth;
    rcSrc.h = g_uiHeight;

    Trans.hHandle = g_hTsOsdToVdo;
    Trans.bInverse = FALSE;
    Trans.Method = COORDTS_METHOD_FULL_FIT;
    Trans.pRcSrc = &rcSrc;
    Trans.pRcDst = &rcDst;
    Trans.uiRectNum = sizeof(rcSrc)/sizeof(rcDst);
    CoordTs_TransRect(&Trans);
    PB_ConfigVdoWIN(PBDISP_IDX_PRI, &rcDst);

//#NT#2012/11/22#Scottie -begin
//#NT#Support Dual Display for PB
    if(TRUE == CfgDisp.bDual)
    {
        Target.SizeTarget.w = CfgDisp.Desc[DISPSRV_DISP_IDX_SECONDARY].pDisp[0].Width;
        Target.SizeTarget.h = CfgDisp.Desc[DISPSRV_DISP_IDX_SECONDARY].pDisp[0].Height;
        Target.pRcRegion = NULL;
        CoordTs_SetTarget(&Target);

        rcSrc.x = g_uiStartX;
        rcSrc.y = g_uiStartY;
        rcSrc.w = g_uiWidth;
        rcSrc.h = g_uiHeight;

        Trans.hHandle = g_hTsOsdToVdo;
        Trans.bInverse = FALSE;
        Trans.Method = COORDTS_METHOD_FULL_FIT;
        Trans.pRcSrc = &rcSrc;
        Trans.pRcDst = &rcDst;
        Trans.uiRectNum = sizeof(rcSrc)/sizeof(rcDst);
        CoordTs_TransRect(&Trans);
        PB_ConfigVdoWIN(PBDISP_IDX_SEC, &rcDst);
    }
//#NT#2012/11/22#Scottie -end

    UIPlayCommTraceMsg("OSD URECT=%d, %d, %d, %d => VIDEO URECT=%d, %d, %d, %d\r\n",
                      rcSrc.x,rcSrc.y,rcSrc.w,rcSrc.h,
                      rcDst.x,rcDst.y,rcDst.w,rcDst.h);
}
//#NT#2011/01/31#Ben Wang -end

INT32 UIPlay_PlaySingle(UINT32 Command)
{
    PLAY_SINGLE_OBJ FlowPlaySingleObj = {0};
    FlowPlaySingleObj.PlayCommand = Command;
    if(0 == (Command & PB_SINGLE_THUMB))
    {
        FlowPlaySingleObj.PlayCommand |= PB_SINGLE_PRIMARY;
    }
    FlowPlaySingleObj.JumpOffset  = 1;
#if (_SCREENNAIL_SIZE_ == _SCREENNAIL_SIZE_VGA_)
#if (HDMI_FUNC == ENABLE)
    if(IsHDMIPlugIn())
    {
        FlowPlaySingleObj.PlayCommand |= PB_SINGLE_NO_HIDDEN;
    }
#endif
#endif
    PB_PlaySingleMode(&FlowPlaySingleObj);
    return PB_WaitCommandFinish(PB_WAIT_INFINITE);
}

