
#----------------------------------------------------------------------
# set the library name here
#----------------------------------------------------------------------
PRJ_NAME = IPL_IMX083_SAMPLE_FF

#----------------------------------------------------------------------
# add/delete source files here
#----------------------------------------------------------------------
SRC = \
	IPL_Cmd_IMX083_Sample_FF.c \
	IPL_Mode_IMX083_Sample_FF.c \
	IPL_Isr_IMX083_Sample_FF.c \
	IPL_Buf_IMX083_Sample_FF.c \
	IPL_dzoomTab_IMX083_Sample_FF.c \
	IPL_Ctrl_IMX083_Sample_FF.c \
	IPL_CtrlNormal_IMX083_Sample_FF.c \
	IPL_CtrlFWPProc_IMX083_Sample_FF.c \
	IPL_CtrlFW_IMX083_Sample_FF.c \
	IPL_D2DCB_IMX083_Sample_FF.c \
	IPL_FlowCB_IMX083_Sample_FF.c \
    IQS_SettingFlow_IMX083_Sample_FF.c \
    IQS_SettingTable_IMX083_Sample_FF.c \
    IQS_ImageEffectTable_IMX083_Sample_FF.c

ASM =

#----------------------------------------------------------------------
# set the include directory here
#----------------------------------------------------------------------
INC_DIR = . \
	../../../../Include \
	../../DevCamCAL \
	../../../../Lib/Lib_src/DevCam/IPL_COMMON \

#----------------------------------------------------------------------
# set the image output directory here
#----------------------------------------------------------------------
IMG_BASE_DIR = ../../../../ARC/Lib

#----------------------------------------------------------------------
# add additional C and assembly flags here
#----------------------------------------------------------------------
CFLAGS_D =
ASMFLAGS_D =

CFLAGS_R =
ASMFLAGS_R =

#----------------------------------------------------------------------
# include common parts of the makefile
#----------------------------------------------------------------------
MAKE_COMMON_DIR = ../../../../MakeCommon
include $(MAKE_COMMON_DIR)/OutputLib.txt
