
#----------------------------------------------------------------------
# set the library name here
#----------------------------------------------------------------------
PRJ_NAME = IPL_OV2710_EVB_FF

#----------------------------------------------------------------------
# add/delete source files here
#----------------------------------------------------------------------
SRC = \
	IPL_Cmd_OV2710_EVB_FF.c \
	IPL_Mode_OV2710_EVB_FF.c \
	IPL_Isr_OV2710_EVB_FF.c \
	IPL_Buf_OV2710_EVB_FF.c \
	IPL_dzoomTab_OV2710_EVB_FF.c \
	IPL_Ctrl_OV2710_EVB_FF.c \
	IPL_CtrlNormal_OV2710_EVB_FF.c \
	IPL_CtrlFWPProc_OV2710_EVB_FF.c \
	IPL_CtrlFW_OV2710_EVB_FF.c \
	IPL_D2DCB_OV2710_EVB_FF.c \
	IPL_FlowCB_OV2710_EVB_FF.c \
    IQS_SettingFlow_OV2710_EVB_FF.c \
    IQS_SettingTable_OV2710_EVB_FF.c \
    IQS_ImageEffectTable_OV2710_EVB_FF.c

ASM =

#----------------------------------------------------------------------
# set the include directory here
#----------------------------------------------------------------------
INC_DIR = . \
	../../../../Include \
	../../../../Lib/Lib_src/DevCam/IPL_COMMON \

#----------------------------------------------------------------------
# set the image output directory here
#----------------------------------------------------------------------
IMG_BASE_DIR = ../../../../ARC/Lib

#----------------------------------------------------------------------
# add additional C and assembly flags here
#----------------------------------------------------------------------
CFLAGS_D =
ASMFLAGS_D =

CFLAGS_R =
ASMFLAGS_R =

#----------------------------------------------------------------------
# include common parts of the makefile
#----------------------------------------------------------------------
MAKE_COMMON_DIR = ../../../../MakeCommon
include $(MAKE_COMMON_DIR)/OutputLib.txt
