/*//////////////////////////////////////////////////////////////////////////////

 ---------- Document Info ---------------

        Author : Anonymous
       Created : 15:18:17, Mar 22 2013
 Last modified : 15:18:17, Mar 22 2013
   Making tool : UI Designer Studio
   File format : C language header file

 ----------- Object Info ----------------

         Class : IMAGE_TABLE
          Name : DemoKit_Image

*///////////////////////////////////////////////////////////////////////////////

#ifndef _DEMOKIT_IMAGE_H_
#define _DEMOKIT_IMAGE_H_

// IMAGE_TABLE
extern const
unsigned char gDemoKit_Image[];

// IMAGE ID
#define ICON__EMPTY                              0x0000
#define ICON_AP_MACHINE_OFF                      0x0001
#define ICON_AP_MACHINE_ON                       0x0002
#define ICON_AUTOSHUTDOWN                        0x0003
#define ICON_AUTOSHUTDOWN_3MIN                   0x0004
#define ICON_AUTOSHUTDOWN_5MIN                   0x0005
#define ICON_AUTOSHUTDOWN_10MIN                  0x0006
#define ICON_AUTOSHUTDOWN_OFF                    0x0007
#define ICON_BACKLIGHT                           0x0008
#define ICON_BACKLIGHT_HIGH                      0x0009
#define ICON_BACKLIGHT_LOW                       0x000A
#define ICON_BACKLIGHT_MID                       0x000B
#define ICON_BACKLIGHT_OFF                       0x000C
#define ICON_BATTERY_CHARGE                      0x000D
#define ICON_BATTERY_EMPTY                       0x000E
#define ICON_BATTERY_FULL                        0x000F
#define ICON_BATTERY_LOW                         0x0010
#define ICON_BATTERY_MED                         0x0011
#define ICON_BATTERY_TYPE                        0x0012
#define ICON_BATTERY_ZERO                        0x0013
#define ICON_BUST                                0x0014
#define ICON_BUST_3SHOT                          0x0015
#define ICON_BUST_CONTINUE                       0x0016
#define ICON_BUST_OFF                            0x0017
#define ICON_CAM_PTZ_OFF                         0x0018
#define ICON_CAM_PTZ_ON                          0x0019
#define ICON_CANCEL                              0x001A
#define ICON_CLOUD_CONNECTED                     0x001B
#define ICON_CLOUD_CONNECTING                    0x001C
#define ICON_CLOUD_DOWNLOAD1                     0x001D
#define ICON_CLOUD_DOWNLOAD2                     0x001E
#define ICON_CLOUD_FAIL                          0x001F
#define ICON_CLOUD_OFF                           0x0020
#define ICON_CLOUD_ON                            0x0021
#define ICON_CLOUD_UPLOAD1                       0x0022
#define ICON_CLOUD_UPLOAD2                       0x0023
#define ICON_COLOR                               0x0024
#define ICON_COPY_FROM_CARD                      0x0025
#define ICON_CYCLIC_REC                          0x0026
#define ICON_CYCLIC_REC_1MIN                     0x0027
#define ICON_CYCLIC_REC_2MIN                     0x0028
#define ICON_CYCLIC_REC_3MIN                     0x0029
#define ICON_CYCLIC_REC_5MIN                     0x002A
#define ICON_CYCLIC_REC_10MIN                    0x002B
#define ICON_CYCLIC_REC_15MIN                    0x002C
#define ICON_DATE_PRINT                          0x002D
#define ICON_DATE_STAMPING                       0x002E
#define ICON_DATE_TIME                           0x002F
#define ICON_DATETIME_SETUP                      0x0030
#define ICON_DDD_OFF                             0x0031
#define ICON_DDD_ON                              0x0032
#define ICON_DEFAULT                             0x0033
#define ICON_DELETE                              0x0034
#define ICON_DELETE_ALL                          0x0035
#define ICON_DELETE_CURRENT                      0x0036
#define ICON_DIR_DOWN                            0x0037
#define ICON_DIR_LEFT                            0x0038
#define ICON_DIR_RIGHT                           0x0039
#define ICON_DIR_UP                              0x003A
#define ICON_DPOF                                0x003B
#define ICON_DUALCAM_BEHIND                      0x003C
#define ICON_DUALCAM_BOTH                        0x003D
#define ICON_DUALCAM_FRONT                       0x003E
#define ICON_EV                                  0x003F
#define ICON_EV_M0P3                             0x0040
#define ICON_EV_M0P6                             0x0041
#define ICON_EV_M1P0                             0x0042
#define ICON_EV_M1P3                             0x0043
#define ICON_EV_M1P6                             0x0044
#define ICON_EV_M2P0                             0x0045
#define ICON_EV_P0P0                             0x0046
#define ICON_EV_P0P3                             0x0047
#define ICON_EV_P0P6                             0x0048
#define ICON_EV_P1P0                             0x0049
#define ICON_EV_P1P3                             0x004A
#define ICON_EV_P1P6                             0x004B
#define ICON_EV_P2P0                             0x004C
#define ICON_FACE_OFF                            0x004D
#define ICON_FACE_ON                             0x004E
#define ICON_FB_LEFT                             0x004F
#define ICON_FCW_OFF                             0x0050
#define ICON_FCW_ON                              0x0051
#define ICON_FF_RIGHT                            0x0052
#define ICON_FILE_VIDEO                          0x0053
#define ICON_FIRMWARE_UPDATE                     0x0054
#define ICON_FLASH_AUTO                          0x0055
#define ICON_FLASH_OFF                           0x0056
#define ICON_FLASH_ON                            0x0057
#define ICON_FLASH_REC                           0x0058
#define ICON_FLASH_RED_EYE                       0x0059
#define ICON_FLICK_50HZ                          0x005A
#define ICON_FLICK_60HZ                          0x005B
#define ICON_FORMAT                              0x005C
#define ICON_G_SENSOR                            0x005D
#define ICON_G_SENSOR_HIGH                       0x005E
#define ICON_G_SENSOR_LOW                        0x005F
#define ICON_G_SENSOR_MID                        0x0060
#define ICON_G_SENSOR_OFF                        0x0061
#define ICON_GOLF_REC                            0x0062
#define ICON_GPS_OFF                             0x0063
#define ICON_GPS_ON                              0x0064
#define ICON_HDR                                 0x0065
#define ICON_HDR_OFF                             0x0066
#define ICON_HELP                                0x0067
#define ICON_HINT_BAR                            0x0068
#define ICON_HZ                                  0x0069
#define ICON_HZ_50                               0x006A
#define ICON_HZ_60                               0x006B
#define ICON_INFO                                0x006C
#define ICON_INTERNAL_FLASH                      0x006D
#define ICON_IRCUT_AUTO                          0x006E
#define ICON_IRCUT_OFF                           0x006F
#define ICON_IRCUT_ON                            0x0070
#define ICON_ISO                                 0x0071
#define ICON_ISO_100                             0x0072
#define ICON_ISO_200                             0x0073
#define ICON_ISO_400                             0x0074
#define ICON_ISO_800                             0x0075
#define ICON_ISO_1600                            0x0076
#define ICON_ISO_AUTO                            0x0077
#define ICON_LANDSCAPE                           0x0078
#define ICON_LANGUAGE                            0x0079
#define ICON_LDWS_OFF                            0x007A
#define ICON_LDWS_ON                             0x007B
#define ICON_LOCAL_STATION__OFF                  0x007C
#define ICON_LOCAL_STATION__ON                   0x007D
#define ICON_LOCK                                0x007E
#define ICON_LOCK_ALL                            0x007F
#define ICON_LOCK_CURRENT                        0x0080
#define ICON_LOCK_UNLOCK                         0x0081
#define ICON_LOCK_UNLOKC_ALL                     0x0082
#define ICON_MENU_FLASH_REC                      0x0083
#define ICON_MENU_MODECHANG                      0x0084
#define ICON_MENU_PLAYBACK_OFF                   0x0085
#define ICON_MENU_PLAYBACK_ON                    0x0086
#define ICON_MENU_PRINT_OFF                      0x0087
#define ICON_MENU_RETURN                         0x0088
#define ICON_MENU_SETUP_OFF                      0x0089
#define ICON_MENU_SETUP_ON                       0x008A
#define ICON_MENU_STILL_OFF                      0x008B
#define ICON_MENU_STILL_ON                       0x008C
#define ICON_MENU_UNDERBAR                       0x008D
#define ICON_MENU_VIDEO_OFF                      0x008E
#define ICON_MENU_VIDEO_ON                       0x008F
#define ICON_MENU_WDR                            0x0090
#define ICON_MENU_WDR_OFF                        0x0091
#define ICON_METERING                            0x0092
#define ICON_MODE_CAPTURE                        0x0093
#define ICON_MODE_PLAYBACK                       0x0094
#define ICON_MODE_VIDEO                          0x0095
#define ICON_MOTION_DET_OFF                      0x0096
#define ICON_MOTION_DET_ON                       0x0097
#define ICON_NO                                  0x0098
#define ICON_OK                                  0x0099
#define ICON_OK2                                 0x009A
#define ICON_PICTBRIDGE_S                        0x009B
#define ICON_PIM_OFF                             0x009C
#define ICON_PIM_ON                              0x009D
#define ICON_PLAY_BACKWARD                       0x009E
#define ICON_PLAY_FORWARD                        0x009F
#define ICON_PLAY_PAUSE                          0x00A0
#define ICON_PLAY_PLAY                           0x00A1
#define ICON_PLAY_STEP                           0x00A2
#define ICON_PLAY_STOP                           0x00A3
#define ICON_POWER_OFF                           0x00A4
#define ICON_PRINT                               0x00A5
#define ICON_PROTECT                             0x00A6
#define ICON_QUALITY                             0x00A7
#define ICON_QUALITY_BASIC                       0x00A8
#define ICON_QUALITY_FINE                        0x00A9
#define ICON_QUALITY_NORMAL                      0x00AA
#define ICON_QUICK_REVIEW                        0x00AB
#define ICON_REC_RECOVERY                        0x00AC
#define ICON_RESOLUTION                          0x00AD
#define ICON_ROTATE                              0x00AE
#define ICON_RSC_OFF                             0x00AF
#define ICON_RSC_ON                              0x00B0
#define ICON_SCENE_MODE                          0x00B1
#define ICON_SCENE_MODE_AUTO                     0x00B2
#define ICON_SCENE_MODE_LANDSCPE                 0x00B3
#define ICON_SCENE_MODE_PORTRIAL                 0x00B4
#define ICON_SCREENSAVER                         0x00B5
#define ICON_SCREENSAVER_3MIN                    0x00B6
#define ICON_SCREENSAVER_5MIN                    0x00B7
#define ICON_SCREENSAVER_10MIN                   0x00B8
#define ICON_SCREENSAVER_OFF                     0x00B9
#define ICON_SD_CARD                             0x00BA
#define ICON_SD_LOCK                             0x00BB
#define ICON_SEL_BAR                             0x00BC
#define ICON_SEL_BAR_BEGIN                       0x00BD
#define ICON_SEL_BAR_DATE                        0x00BE
#define ICON_SEL_BAR_END                         0x00BF
#define ICON_SEL_BAR_ITEM                        0x00C0
#define ICON_SEL_BAR_MED                         0x00C1
#define ICON_SEL_BAR_YEAR                        0x00C2
#define ICON_SELFTIMER                           0x00C3
#define ICON_SELFTIMER_2SEC                      0x00C4
#define ICON_SELFTIMER_5SEC                      0x00C5
#define ICON_SELFTIMER_10SEC                     0x00C6
#define ICON_SELFTIMER_OFF                       0x00C7
#define ICON_SEQUENCE_NO                         0x00C8
#define ICON_SHAKE_OFF                           0x00C9
#define ICON_SHAKE_ON                            0x00CA
#define ICON_SHARPNESS                           0x00CB
#define ICON_SHARPNESS_HIGH                      0x00CC
#define ICON_SHARPNESS_LOW                       0x00CD
#define ICON_SHARPNESS_MED                       0x00CE
#define ICON_SIGNAL_0STEP                        0x00CF
#define ICON_SIGNAL_0STEP_M                      0x00D0
#define ICON_SIGNAL_1STEP                        0x00D1
#define ICON_SIGNAL_1STEP_M                      0x00D2
#define ICON_SIGNAL_2STEP                        0x00D3
#define ICON_SIGNAL_2STEP_M                      0x00D4
#define ICON_SIGNAL_3STEP                        0x00D5
#define ICON_SIGNAL_4STEP                        0x00D6
#define ICON_SIGNAL_5STEP                        0x00D7
#define ICON_SLIDESHOW                           0x00D8
#define ICON_SLIDESHOW_2SEC                      0x00D9
#define ICON_SLIDESHOW_5SEC                      0x00DA
#define ICON_SLIDESHOW_8SEC                      0x00DB
#define ICON_SLIDESHOW_OFF                       0x00DC
#define ICON_SMILE                               0x00DD
#define ICON_SOUND_REC_OFF                       0x00DE
#define ICON_SOUND_REC_ON                        0x00DF
#define ICON_SPEAKER                             0x00E0
#define ICON_SYS_CAL                             0x00E1
#define ICON_TIME_LAPSE_OFF                      0x00E2
#define ICON_TIME_LAPSE_ON                       0x00E3
#define ICON_TITLE_BAR                           0x00E4
#define ICON_TV_MODE                             0x00E5
#define ICON_TV_NTSC                             0x00E6
#define ICON_TV_PAL                              0x00E7
#define ICON_URGENT_PROTECT_AUTO                 0x00E8
#define ICON_URGENT_PROTECT_MANUAL               0x00E9
#define ICON_USB_MSDC                            0x00EA
#define ICON_USB_OFF                             0x00EB
#define ICON_USB_ON                              0x00EC
#define ICON_USB_UVC                             0x00ED
#define ICON_VERSION                             0x00EE
#define ICON_VIDEO_FLIP_OFF                      0x00EF
#define ICON_VIDEO_FLIP_ON                       0x00F0
#define ICON_VOICE                               0x00F1
#define ICON_VOL_0                               0x00F2
#define ICON_VOL_1                               0x00F3
#define ICON_VOL_2                               0x00F4
#define ICON_WB                                  0x00F5
#define ICON_WB_AUTO                             0x00F6
#define ICON_WB_CLOUDY                           0x00F7
#define ICON_WB_DAYLIGHT                         0x00F8
#define ICON_WB_FLUORESCENT                      0x00F9
#define ICON_WB_TUNGSTEN                         0x00FA
#define ICON_WEB_SITE_OFF                        0x00FB
#define ICON_WEB_SITE_ON                         0x00FC
#define ICON_WIFI_CONNECTED                      0x00FD
#define ICON_WIFI_CONNECTING1                    0x00FE
#define ICON_WIFI_CONNECTING2                    0x00FF
#define ICON_WIFI_CONNECTING3                    0x0100
#define ICON_WIFI_DOT_CONNECTING_OFF             0x0101
#define ICON_WIFI_DOT_CONNECTING_ON              0x0102
#define ICON_WIFI_FAIL                           0x0103
#define ICON_WIFI_OFF                            0x0104
#define ICON_WIFI_ON                             0x0105
#define ICON_WIFI_ON_M                           0x0106
#define ICON_YES                                 0x0107
#define ICON_ADAS_CAL                            0x0108

#endif //_DEMOKIT_IMAGE_H_
