//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYSLIDESHOWCB_H
#define UIMENUWNDPLAYSLIDESHOWCB_H

#include "UIFramework.h"

extern VControl UIMenuWndPlaySlideShowCBCtrl;//Panel type 

//---------------------UIMenuWndPlaySlideShowCBCtrl User Export---------------------------
#endif
