#include "LensAPI.h"
#include "SysKer.h"
#include "LensCtrlTsk.h"

#define PRI_LENSCTRL2            8
#define STKSIZE_LENSCTRL2        1024
#define PRI_LENSCTRLBG           9
#define STKSIZE_LENSCTRLBG       2048

UINT32 FLG_ID_LENS2 = 0;
UINT32 LENSCTRLTSK2_ID = 0;
UINT32 FLG_ID_LENSBG = 0;
UINT32 LENSCTRLTSKBG_ID = 0;

void LensCtrl2_InstallID(void)
{
    OS_CONFIG_FLAG(FLG_ID_LENS2);
    OS_CONFIG_TASK(LENSCTRLTSK2_ID, PRI_LENSCTRL2,  STKSIZE_LENSCTRL2,   LensCtrlTsk2);
    OS_CONFIG_FLAG(FLG_ID_LENSBG);
    OS_CONFIG_TASK(LENSCTRLTSKBG_ID, PRI_LENSCTRLBG,  STKSIZE_LENSCTRLBG,   LensCtrlBGTsk);
}
