//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWRNMSG_H
#define UIFLOWWNDWRNMSG_H

#include "UIFramework.h"

extern VControl UIFlowWndWrnMsgCtrl;//Panel type 

extern VControl UIFlowWndWrnMsg_StatusTXT_MsgCtrl;//Status type 

typedef enum
{
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORY_FULL,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORYERROR,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARD_FULL,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARDERROR,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARD_LOCKED,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_FILE_PROTECT,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NO_IMAGE,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NO_CARD,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_FOLDERFULL,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NOT_JPEG,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NO_FILE,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PICTUREERROR,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CLUSTER_WRONG,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_SD_CLASS4,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_SD_CLASS6,
UIFlowWndWrnMsg_StatusTXT_Msg_MAX
}UIFlowWndWrnMsg_StatusTXT_Msg_Setting;

//---------------------UIFlowWndWrnMsgCtrl User Export---------------------------
#endif
