//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIFlowWndWaitMomentRes.c"
#include "UIFlow.h"
//-----------------------------------------------------------------------------
// UIFlowWndWaitMoment User Variable & Function Declarations
//-----------------------------------------------------------------------------
static UINT32 g_uiWaitMomentMsg     = 0;

//---------------------UIFlowWndWaitMomentCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndWaitMoment)
CTRL_LIST_ITEM(UIFlowWndWaitMoment_StatusTXT_Msg)
CTRL_LIST_END

//----------------------UIFlowWndWaitMomentCtrl Event---------------------------
INT32 UIFlowWndWaitMoment_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWaitMoment_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWaitMoment_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWaitMoment_OnBackgroundDone(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndWaitMoment)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndWaitMoment_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndWaitMoment_OnClose)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndWaitMoment_OnTimer)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE,UIFlowWndWaitMoment_OnBackgroundDone)
EVENT_END

INT32 UIFlowWndWaitMoment_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum > 0)
    {
        g_uiWaitMomentMsg = paramArray[0];
        debug_ind(("UIFlowWndWaitMoment: Msg = 0x%x\r\n", g_uiWaitMomentMsg));
    }
    UxState_SetData(&UIFlowWndWaitMoment_StatusTXT_MsgCtrl,STATE_CURITEM,g_uiWaitMomentMsg);
    UxCtrl_SetShow(&UIFlowWndWaitMoment_StatusTXT_MsgCtrl,TRUE);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWaitMoment_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWaitMoment_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWaitMoment_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVTEVT event;
    UINT32 uiReturn = 0;
    UINT32 status;

    event = paramArray[ONDONE_PARAM_INDEX_CMD];
    status = paramArray[ONDONE_PARAM_INDEX_RET];
    debug_ind(("UIFlowWndWaitMoment OnBackgroundDone event = 0x%x, status=%d\r\n", event, status));

    switch(event)
    {
        case NVTEVT_BKW_COPY2CARD:
        {
            switch(status)
            {
            case 1: // TRUE
                uiReturn = NVTRET_COPY2CARD;
                break;
            case 0:
                uiReturn = NVTRET_CANCEL;
            }
            //Rsvd
            break;
        }

        case NVTEVT_BKW_DELALL:
        {
            uiReturn = NVTRET_DELETEALL;
            //Rsvd
            break;
        }


        case NVTEVT_BKW_FORMAT_CARD:
        {
            uiReturn = NVTRET_FORMAT;
            //Rsvd
            break;
        }

        case NVTEVT_BKW_FORMAT_NAND:
        {
            uiReturn = NVTRET_FORMAT;
            //Rsvd
            break;
        }

        case NVTEVT_BKW_FORMAT:
        {
            uiReturn = NVTRET_FORMAT;
            //Rsvd
            break;
        }

        case NVTEVT_BKW_SETPROTECT:
        {
            uiReturn = NVTRET_PROTECT;
            //Rsvd
            break;
        }
        case NVTEVT_BKW_WIFI_ON:
        {
            Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, PRIMARY_MODE_MOVIE,SYS_SUBMODE_WIFI);
            return NVTEVT_CONSUME;
        }
        default:
            uiReturn = NVTRET_ERROR;
            debug_err(("UIFlowWndWaitMoment OnBackgroundDone: Unknown event 0x%x\r\n", event));
            break;
    }

    Ux_CloseWindow(pCtrl, 2, NVTRET_WAITMOMENT, uiReturn);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndWaitMoment_StatusTXT_MsgCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndWaitMoment_StatusTXT_Msg)
EVENT_END

