//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDBATTERYLOW_H
#define UIFLOWWNDBATTERYLOW_H

#include "UIFramework.h"

extern VControl UIFlowWndBatteryLowCtrl;//Panel type 

extern VControl UIFlowWndBatteryLow_Static_TitleCtrl;//Static type 

extern VControl UIFlowWndBatteryLow_PanelCtrl;//Tab type 

typedef enum
{
UIFlowWndBatteryLow_Panel_UIFlowWndBatteryLow_Static_PowerOffY,
UIFlowWndBatteryLow_Panel_UIFlowWndBatteryLow_Static_PowerOffN,
UIFlowWndBatteryLow_Panel_MAX
}UIFlowWndBatteryLow_Panel_Setting;

extern VControl UIFlowWndBatteryLow_Static_PowerOffYCtrl;//Static type 

extern VControl UIFlowWndBatteryLow_Static_PowerOffNCtrl;//Static type 

extern VControl UIFlowWndBatteryLow_SecondCtrl;//Static type 

extern VControl UIFlowWndBatteryLow_SwitchCtrl;//Menu type 

typedef enum
{
UIFlowWndBatteryLow_Switch_STRID_YES,
UIFlowWndBatteryLow_Switch_STRID_NO,
UIFlowWndBatteryLow_Switch_MAX
}UIFlowWndBatteryLow_Switch_Setting;

//---------------------UIFlowWndBatteryLowCtrl User Export---------------------------
#endif
