
#----------------------------------------------------------------------
# set the library name here
#----------------------------------------------------------------------
PRJ_NAME = IPL_GC2023P_TVP5150_CARDV_FFFF

#----------------------------------------------------------------------
# add/delete source files here
#----------------------------------------------------------------------
SRC = \
	IPL_Cmd_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_Mode_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_Isr_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_Buf_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_dzoomTab_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_Ctrl_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_CtrlNormal_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_CtrlFWPProc_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_CtrlFW_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_CtrlFWD_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_D2DCB_GC2023P_TVP5150_CARDV_FFFF.c \
	IPL_FlowCB_GC2023P_TVP5150_CARDV_FFFF.c \
  IQS_SettingFlow_GC2023P_TVP5150_CARDV_FFFF.c \
  IQS_SettingTable_GC2023P_TVP5150_CARDV_FFFF.c \
  IQS_ImageEffectTable_GC2023P_TVP5150_CARDV_FFFF.c

ASM =

#----------------------------------------------------------------------
# set the include directory here
#----------------------------------------------------------------------
INC_DIR = . \
	../../../../Include \
	../../../../Lib/Lib_src/DevCam/IPL_COMMON \

#----------------------------------------------------------------------
# set the image output directory here
#----------------------------------------------------------------------
IMG_BASE_DIR = ../../../../ARC/Lib

#----------------------------------------------------------------------
# add additional C and assembly flags here
#----------------------------------------------------------------------
CFLAGS_D =
ASMFLAGS_D =

CFLAGS_R =
ASMFLAGS_R =

#----------------------------------------------------------------------
# include common parts of the makefile
#----------------------------------------------------------------------
MAKE_COMMON_DIR = ../../../../MakeCommon
include $(MAKE_COMMON_DIR)/OutputLib.txt
