//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDMOVIE_H
#define UIFLOWWNDMOVIE_H

#include "UIFramework.h"

#define UIFlowWndMovie_Restart_Rec      0x5a5a
extern VControl UIFlowWndMovieCtrl;//Panel type

extern VControl UIFlowWndMovie_Static_cameraCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_CyclicRecCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_CyclicRec_ICONID_NULL,
UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_1MIN,
UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_3MIN,
UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_5MIN,
UIFlowWndMovie_Status_CyclicRec_ICON_CYCLIC_REC_10MIN,
UIFlowWndMovie_Status_CyclicRec_MAX
}UIFlowWndMovie_Status_CyclicRec_Setting;

extern VControl UIFlowWndMovie_Status_MotionDetCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_MotionDet_ICONID_NULL,
UIFlowWndMovie_Status_MotionDet_ICON_FLASH_REC,
UIFlowWndMovie_Status_MotionDet_MAX
}UIFlowWndMovie_Status_MotionDet_Setting;

extern VControl UIFlowWndMovie_Status_batteryCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_battery_ICON_BATTERY_FULL,
UIFlowWndMovie_Status_battery_ICON_BATTERY_MED,
UIFlowWndMovie_Status_battery_ICON_BATTERY_LOW,
UIFlowWndMovie_Status_battery_ICON_BATTERY_EMPTY,
UIFlowWndMovie_Status_battery_ICON_BATTERY_ZERO,
UIFlowWndMovie_Status_battery_ICON_BATTERY_CHARGE,
UIFlowWndMovie_Status_battery_MAX
}UIFlowWndMovie_Status_battery_Setting;

extern VControl UIFlowWndMovie_YMD_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_HMS_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_PanelCtrl;//Panel type 

extern VControl UIFlowWndMovie_Status_StorageCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_Storage_ICON_INTERNAL_FLASH,
UIFlowWndMovie_Status_Storage_ICON_SD_CARD,
UIFlowWndMovie_Status_Storage_ICON_SD_LOCK,
UIFlowWndMovie_Status_Storage_MAX
}UIFlowWndMovie_Status_Storage_Setting;

extern VControl UIFlowWndMovie_Static_timeCtrl;//Static type 

extern VControl UIFlowWndMovie_Static_maxtimeCtrl;//Static type 

extern VControl UIFlowWndMovie_Static_resolutionCtrl;//Static type 

extern VControl UIFlowWndMovie_Zoom_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_StatusICN_EVCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_StatusICN_EV_ICON_EV_P2P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P1P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_P0P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M0P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M0P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P0,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P3,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M1P6,
UIFlowWndMovie_StatusICN_EV_ICON_EV_M2P0,
UIFlowWndMovie_StatusICN_EV_MAX
}UIFlowWndMovie_StatusICN_EV_Setting;

extern VControl UIFlowWndMovie_Status_HDRCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_HDR_ICONID_NULL,
UIFlowWndMovie_Status_HDR_ICON_HDR,
UIFlowWndMovie_Status_HDR_MAX
}UIFlowWndMovie_Status_HDR_Setting;

extern VControl UIFlowWndMovie_StaticIcon_PIMCCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_WifiStatusCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_WifiStatus_ICON_WIFI_FAIL,
UIFlowWndMovie_Status_WifiStatus_ICON_WIFI_ON,
UIFlowWndMovie_Status_WifiStatus_MAX
}UIFlowWndMovie_Status_WifiStatus_Setting;

//---------------------UIFlowWndMovieCtrl User Export---------------------------
#endif
