
#----------------------------------------------------------------------
# set the library name here
#----------------------------------------------------------------------
PRJ_NAME = IPL_AR0330_TVP5150_CARDV_FFFF

#----------------------------------------------------------------------
# add/delete source files here
#----------------------------------------------------------------------
SRC = \
	IPL_Cmd_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_Mode_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_Isr_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_Buf_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_dzoomTab_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_Ctrl_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_CtrlNormal_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_CtrlFWPProc_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_CtrlFW_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_CtrlFWD_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_D2DCB_AR0330_TVP5150_CARDV_FFFF.c \
	IPL_FlowCB_AR0330_TVP5150_CARDV_FFFF.c \
  IQS_SettingFlow_AR0330_TVP5150_CARDV_FFFF.c \
  IQS_SettingTable_AR0330_TVP5150_CARDV_FFFF.c \
  IQS_ImageEffectTable_AR0330_TVP5150_CARDV_FFFF.c

ASM =

#----------------------------------------------------------------------
# set the include directory here
#----------------------------------------------------------------------
INC_DIR = . \
	../../../../Include \
	../../../../Lib/Lib_src/DevCam/IPL_COMMON \

#----------------------------------------------------------------------
# set the image output directory here
#----------------------------------------------------------------------
IMG_BASE_DIR = ../../../../ARC/Lib

#----------------------------------------------------------------------
# add additional C and assembly flags here
#----------------------------------------------------------------------
CFLAGS_D =
ASMFLAGS_D =

CFLAGS_R =
ASMFLAGS_R =

#----------------------------------------------------------------------
# include common parts of the makefile
#----------------------------------------------------------------------
MAKE_COMMON_DIR = ../../../../MakeCommon
include $(MAKE_COMMON_DIR)/OutputLib.txt
