#ifndef IPL_CTRL_DZOOM_H_
#define IPL_CTRL_DZOOM_H_

#include "type.h"
#include "IPL_HAL_Stripe_Int.h"
#include "IPL_HAL_DCE_Info.h"

#define FLGPTN_DZOOM_IDLE   0x00000001
#define FLGPTN_DZOOM_IDLE_2 0x00000002
//sie
#define FLGPTN_DZOOM_SIE    0x00000010
#define FLGPTN_DZOOM_SIE_1  0x00000020
#define FLGPTN_DZOOM_SIE_2  0x00000040
#define FLGPTN_DZOOM_SIE_3  0x00000080
//SIE2
#define FLGPTN_DZOOM_SIE2   0x00000100
#define FLGPTN_DZOOM_SIE2_1 0x00000200
#define FLGPTN_DZOOM_SIE2_2 0x00000400
//PRE2IME with SIE
#define FLGPTN_DZOOM_PRE    0x00001000
#define FLGPTN_DZOOM_IFE    0x00004000
#define FLGPTN_DZOOM_DCE    0x00010000
#define FLGPTN_DZOOM_IPE    0x00100000
#define FLGPTN_DZOOM_IFE2   0x00400000
#define FLGPTN_DZOOM_IME    0x10000000
#define FLGPTN_DZOOM_IME_1  0x20000000
#define FLGPTN_DZOOM_IME_2  0x40000000
//PRE2IME with SIE2
#define FLGPTN_DZOOM_PRE_2  0x00002000
#define FLGPTN_DZOOM_IFE_2  0x00008000
#define FLGPTN_DZOOM_DCE_2  0x00020000
#define FLGPTN_DZOOM_IPE_2  0x00200000
#define FLGPTN_DZOOM_IFE2_2 0x00800000
#define FLGPTN_DZOOM_IME2   0x40000000
#define FLGPTN_DZOOM_IME2_2 0x80000000

extern ER IPL_DZoomSet(void* ptr, Coordinate *dceinfo, IPH_StripeResult *striprst, IPH_NormResult *normrst, IPL_PROC_ID id);

extern UINT32 IPL_DZoomIsIdle(IPL_PROC_ID id);
extern UINT32 IPL_DZoomChk(IPL_PROC_ID id);
extern void IPL_DZoomProc_FB_SIEISR(UINT32 Flag, UINT32 SIELoad, UINT32 PREIMELoad, volatile IPL_RAW_IMG_INFO *SIEInfo, volatile IPL_RAW_IMG_INFO *PREInfo, IPL_PROC_ID id);

extern void IPL_DZoomProc_FA_SIEISR(UINT32 Flag, UINT32 SIELoad, volatile IPL_RAW_IMG_INFO *SIEInfo, IPL_PROC_ID id);
extern void IPL_DZoomProc_FA_IMEISR(UINT32 Flag, UINT32 PRELoad, volatile IPL_RAW_IMG_INFO *PREInfo, IPL_PROC_ID id);

#define IPL_DZoom_FB_SIE_ISR_ACTST(SIEInfo, PREInfo, Id) IPL_DZoomProc_FB_SIEISR(FLGPTN_DZOOM_SIE, TRUE, FALSE, SIEInfo, PREInfo, Id)
#define IPL_DZoom_FB_SIE_ISR_FMD(SIEInfo, PREInfo, Id) IPL_DZoomProc_FB_SIEISR((FLGPTN_DZOOM_SIE_3|FLGPTN_DZOOM_SIE_2|FLGPTN_DZOOM_SIE_1), TRUE, FALSE, SIEInfo, PREInfo, Id)

#define IPL_DZoom_FC_SIE_ISR_ACTST(SIEInfo, PREInfo, Id) IPL_DZoomProc_FB_SIEISR(FLGPTN_DZOOM_SIE, TRUE, TRUE, SIEInfo, PREInfo, Id)
#define IPL_DZoom_FC_SIE_ISR_FMD(SIEInfo, PREInfo, Id) IPL_DZoomProc_FB_SIEISR((FLGPTN_DZOOM_SIE_3|FLGPTN_DZOOM_SIE_2|FLGPTN_DZOOM_SIE_1), TRUE, TRUE, SIEInfo, PREInfo, Id)

#define IPL_DZoom_FD_SIE_ISR_ACTST(SIEInfo, PREInfo, Id) IPL_DZoomProc_FB_SIEISR(FLGPTN_DZOOM_SIE, TRUE, TRUE, SIEInfo, PREInfo, Id)
#define IPL_DZoom_FD_SIE_ISR_FMD(SIEInfo, PREInfo, Id) IPL_DZoomProc_FB_SIEISR((FLGPTN_DZOOM_SIE_3|FLGPTN_DZOOM_SIE_2|FLGPTN_DZOOM_SIE_1), TRUE, TRUE, SIEInfo, PREInfo, Id)

#define IPL_DZoom_FA_SIE_ISR_ACTST(SIEInfo, Id) IPL_DZoomProc_FA_SIEISR(FLGPTN_DZOOM_SIE, TRUE, SIEInfo, Id)
#define IPL_DZoom_FA_SIE_ISR_FMD(SIEInfo, Id) IPL_DZoomProc_FA_SIEISR((FLGPTN_DZOOM_SIE_2|FLGPTN_DZOOM_SIE_1) ,TRUE, SIEInfo, Id)
#define IPL_DZoom_FA_IME_ISR(PREInfo, Id) IPL_DZoomProc_FA_IMEISR((FLGPTN_DZOOM_IME_2|FLGPTN_DZOOM_IME_1|FLGPTN_DZOOM_IME),TRUE, PREInfo, Id)

#endif //IPL_CTRL_DZOOM_H_

