#ifndef _IPL_CTRLINFOR_INT_H_
#define _IPL_CTRLINFOR_INT_H_
/**
    IPL_CtrlInfor_Int.h


    @file       IPL_CtrlInfor_Int.h
    @ingroup    mISYSAlg
    @note       Nothing (or anything need to be mentioned).

    Copyright   Novatek Microelectronics Corp. 2011.  All rights reserved.
*/
#include "type.h"
#include "ErrorNo.h"

/**
    default information for Image-Pipeline
*/
typedef enum
{
    IPLCTRL_PRVFLOW = 0,
    IPLCTRL_CAPFLOW,

    IPLCTRL_PRVBURSTLENGTH,
    IPLCTRL_CAPBURSTLENGTH,

    IPLCTRL_CUR_MODE,

    IPLCTRL_SEN_PRVCROPRATIO,
    IPLCTRL_SEN_CAPCROPRATIO,

    IPLCTRL_SIE_CH2_CAP_SUBRATIO,

    IPLCTRL_CAP_PRI_V_EN,
    IPLCTRL_CAP_PRI_V_SUBRATIO,

    IPLCTRL_CAP_PRI_CC_EN,
    IPLCTRL_CAP_PRI_CC_SUBRATIO,

    IPLCTRL_CAP_QV_V_EN,
    IPLCTRL_CAP_QV_V_SUBRATIO,

    IPLCTRL_CAP_QV_CC_EN,
    IPLCTRL_CAP_QV_CC_SUBRATIO,

    IPLCTRL_PRVAUTO_OB_EN,
    IPLCTRL_PRVAUTO_SMR_EN,
    IPLCTRL_CAPAUTO_OB_EN,
    IPLCTRL_CAPDF_EN,

    IPLCTRL_SIE_PRVSTPIX,
    IPLCTRL_SIE_CH0_PRVBIT,
    IPLCTRL_SIE_CH2_PRVBIT,
    IPLCTRL_SIE_CAPSTPIX,
    IPLCTRL_SIE_CH0_CAPBIT,
    IPLCTRL_SIE_CH2_CAPBIT,

    IPLCTRL_SIE_PRVCROP_SIZE_H,
    IPLCTRL_SIE_PRVCROP_SIZE_V,

    IPLCTRL_SIE_CAPCROP_SIZE_H,
    IPLCTRL_SIE_CAPCROP_SIZE_V,

    IPLCTRL_SIE_CH0_RAW_EN,
    IPLCTRL_SIE_CH0_RAW_BUFNUM,
    IPLCTRL_SIE_CH0_RAW_SIZE_H,
    IPLCTRL_SIE_CH0_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH0_RAW_SIZE_V,
    IPLCTRL_SIE_CH0_CAP_RAW_SIZE_H,
    IPLCTRL_SIE_CH0_CAP_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH0_CAP_RAW_SIZE_V,

    IPLCTRL_SIE_CH2_RAW_EN,
    IPLCTRL_SIE_CH2_RAW_BUFNUM,
    IPLCTRL_SIE_CH2_RAW_SIZE_H,
    IPLCTRL_SIE_CH2_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH2_RAW_SIZE_V,
    IPLCTRL_SIE_CH2_CAP_RAW_SIZE_H,
    IPLCTRL_SIE_CH2_CAP_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CH2_CAP_RAW_SIZE_V,

    IPLCTRL_SIE_VA_EN,
    IPLCTRL_SIE_VA_BUFNUM,
    IPLCTRL_SIE_CA_EN,
    IPLCTRL_SIE_CA_TYPE,
    IPLCTRL_SIE_CA_WINXNUM,
    IPLCTRL_SIE_CA_WINYNUM,
    IPLCTRL_SIE_CA_BUFNUM,

    IPLCTRL_SIE_ECS_EN,

    IPLCTRL_PRE_IN_BIT,
    IPLCTRL_PRE_IN_SIZE_H,
    IPLCTRL_PRE_IN_SIZE_HLOS,
    IPLCTRL_PRE_IN_SIZE_V,

    IPLCTRL_IPE_OUT_EN,
    IPLCTRL_IPE_OUT_FMT,
    IPLCTRL_IPE_OUT_BUFNUM,
    IPLCTRL_IPE_OUT_SIZE_H,
    IPLCTRL_IPE_OUT_SIZE_HLOS,
    IPLCTRL_IPE_OUT_SIZE_V,

    IPLCTRL_IPE_VA_EN,
    IPLCTRL_IPE_VA_BUFNUM,

    IPLCTRL_IPE_ETH_EN,
    IPLCTRL_IPE_ETH_SIZE_H,
    IPLCTRL_IPE_ETH_SIZE_HLOS,
    IPLCTRL_IPE_ETH_SIZE_V,

    IPLCTRL_IPE_V_EN,
    IPLCTRL_IPE_V_BUFNUM,
    IPLCTRL_IPE_V_SIZE_H,
    IPLCTRL_IPE_V_SIZE_HLOS,
    IPLCTRL_IPE_V_SIZE_V,

    IPLCTRL_IPE_LCA_EN,
    IPLCTRL_IPE_LCA_BUFNUM,
    IPLCTRL_IPE_LCA_SIZE_H,
    IPLCTRL_IPE_LCA_SIZE_HLOS,
    IPLCTRL_IPE_LCA_SIZE_V,

    IPLCTRL_IPEIFE2_LCA_EN,
    IPLCTRL_IPEIFE2_LCA_BUFNUM,

    IPLCTRL_IME_P1_EN,
    IPLCTRL_IME_P1_FMT,
    IPLCTRL_IME_P1_BUFNUM,
    IPLCTRL_IME_P1_BUF_SIZE_H,
    IPLCTRL_IME_P1_BUF_SIZE_V,
    IPLCTRL_IME_P1_ORG_SIZE_H,
    IPLCTRL_IME_P1_ORG_SIZE_HLOS,
    IPLCTRL_IME_P1_ORG_SIZE_V,
    IPLCTRL_IME_P1_OUT_SIZE_H,
    IPLCTRL_IME_P1_OUT_SIZE_HLOS,
    IPLCTRL_IME_P1_OUT_SIZE_V,
    IPLCTRL_IME_P1_DISP_SIZE_H,
    IPLCTRL_IME_P1_DISP_SIZE_HLOS,
    IPLCTRL_IME_P1_DISP_SIZE_V,

    IPLCTRL_IME_P2_EN,
    IPLCTRL_IME_P2_FMT,
    IPLCTRL_IME_P2_BUFNUM,
    IPLCTRL_IME_P2_BUF_SIZE_H,
    IPLCTRL_IME_P2_BUF_SIZE_V,
    IPLCTRL_IME_P2_ORG_SIZE_H,
    IPLCTRL_IME_P2_ORG_SIZE_HLOS,
    IPLCTRL_IME_P2_ORG_SIZE_V,
    IPLCTRL_IME_P2_OUT_SIZE_H,
    IPLCTRL_IME_P2_OUT_SIZE_HLOS,
    IPLCTRL_IME_P2_OUT_SIZE_V,
    IPLCTRL_IME_P2_DISP_SIZE_H,
    IPLCTRL_IME_P2_DISP_SIZE_HLOS,
    IPLCTRL_IME_P2_DISP_SIZE_V,

    IPLCTRL_IME_P3_EN,
    IPLCTRL_IME_P3_FMT,
    IPLCTRL_IME_P3_BUFNUM,
    IPLCTRL_IME_P3_BUF_SIZE_H,
    IPLCTRL_IME_P3_BUF_SIZE_V,
    IPLCTRL_IME_P3_ORG_SIZE_H,
    IPLCTRL_IME_P3_ORG_SIZE_HLOS,
    IPLCTRL_IME_P3_ORG_SIZE_V,
    IPLCTRL_IME_P3_OUT_SIZE_H,
    IPLCTRL_IME_P3_OUT_SIZE_HLOS,
    IPLCTRL_IME_P3_OUT_SIZE_V,
    IPLCTRL_IME_P3_DISP_SIZE_H,
    IPLCTRL_IME_P3_DISP_SIZE_HLOS,
    IPLCTRL_IME_P3_DISP_SIZE_V,

    IPLCTRL_DIS_EN,
    IPLCTRL_DIS_RATIO,

    IPLCTRL_RSC_EN,
    IPLCTRL_RSC_RATIO,

    IPLCTRL_SIE_CCIR_CAP_RAW_SIZE_H,
    IPLCTRL_SIE_CCIR_CAP_RAW_SIZE_HLOS,
    IPLCTRL_SIE_CCIR_CAP_RAW_SIZE_V,
    IPLCTRL_SIE_CCIR_CAPBIT,

    IPLCTRL_MAX_CNT_DEF,
    ENUM_DUMMY4WORD(IPLCTRL_IDX_DEF)
} IPLCTRL_IDX_DEF;

#define IPL_CTRL_ELEMENT_MAX 200
#define IPL_CTRL_NO_USE 0xffffffff

/**
     set ctrl information

     @param[in] IPL_PROC_ID ipl process id
     @param[in] UINT32 idx, depend on IPL lib
     @param[in] UINT32 value
*/
extern void IPL_CtrlSetInfor(UINT32 Id, UINT32 Idx, UINT32 Value);

/**
     get ctrl information

     @param[in] IPL_PROC_ID ipl process id
     @param[in] UINT32 idx, depend on IPL lib
     @return [UINT32]
         - @b value
*/
extern UINT32 IPL_CtrlGetInfor(UINT32 Id, UINT32 Idx);

/**
     initial ctrl information

     @note reset all array information.
     @return (ER)
         - @b E_OK: SUCCESS
         - @b E_SYS: FAIL
*/
extern ER IPL_CtrlInforInit(void);

/**
     un-initial ctrl information

     @note reset all array information.

     @return (ER)
         - @b E_OK: SUCCESS
         - @b E_SYS: FAIL
*/
extern ER IPL_CtrlInforUnInit(void);

#endif //_IPL_CTRLINFOR_INT_H_