//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIMODULELINK_H
#define UIMENUWNDWIFIMODULELINK_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiModuleLinkCtrl;//Panel type 

extern VControl UIMenuWndWiFiModuleLink_StaticICN_WiFiCtrl;//Static type 

extern VControl UIMenuWndWiFiModuleLink_StatusTXT_WiFiModeCtrl;//Status type 

typedef enum
{
UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_STRID_WIFI_AP_MODE,
UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_STRID_WIFI_CLIENT_MODE,
UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_MAX
}UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode_Setting;

extern VControl UIMenuWndWiFiModuleLink_StaticTXT_SSIDCtrl;//Static type 

extern VControl UIMenuWndWiFiModuleLink_StaticTXT_KeyCtrl;//Static type 

extern VControl UIMenuWndWiFiModuleLink_StaticTXT_CancelCtrl;//Static type 

//---------------------UIMenuWndWiFiModuleLinkCtrl User Export---------------------------
#endif
