//This source code is generated by UI Designer Studio.

#ifdef __ECOS
#include "stdio.h"
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiMobileLinkOKRes.c"
#include "WifiAppCmd.h"
#include "UIFlow.h"
#include "UIAppNetwork.h"
#include "rtc.h"
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG        1
#define _UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG        0

#if (_UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)            debug_msg ("^R UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)
#endif

#if (_UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)
#endif

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Global Variables -----------------------------
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
static UINT32  gUIMenuWndWiFiHeartBeatTimerID = NULL_TIMER;
#endif
//#NT#2016/03/23#Isiah Chang -end
static UINT32  gUIMenuWndWiFiMotionDetTimerID = NULL_TIMER;
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_camera)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_CyclicRec)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_MotionDet)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_battery)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_YMD_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_HMS_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Storage)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_time)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_resolution)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Zoom_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusICN_EV)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_HDR)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticIcon_PIMC)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_WifiStatus)
CTRL_LIST_END
char StringMacBuf[32] = {0};
//----------------------UIMenuWndWiFiMobileLinkOKCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExePhotoCapture(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnUpdateInfo(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetPhotoSize(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRec(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieRecSize(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeCyclicRec(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieHDR(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieEV(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMotionDet(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieAudio(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieDateImprint(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieLiveviewSize(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieGSesnorSensitivity(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetAutoRecording(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieRecBitRate(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieLiveviewBitRate(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieLiveviewStart(VControl *, UINT32 , UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeTriggerMovieRawEnc(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);

INT32 UIMenuWndWiFiMobileLinkOK_OnExeModeChange(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetSSID(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetPassphrase(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeDate(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeTime(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExePoweroff(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeLanguage(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeTV(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeFormat(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSysReset(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeFWUpdate(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeReconnect(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSaveMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeRemoveUser(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExePipStyle(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSendSSIDPassphrase(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetWiFiConnectMode(VControl *, UINT32, UINT32 *);

INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeleteFiles(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeleteROFiles(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLinkOK_OnWiFiState(VControl *, UINT32, UINT32 *);
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
INT32 UIMenuWndWiFiMobileLinkOK_OnExeHB(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnAppSessionClose(VControl *, UINT32, UINT32 *);
#endif
//#NT#2016/03/23#Isiah Chang -end


INT32 UIMenuWndWiFiModuleLinkOK_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLinkOK_OnKeyDown(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndWiFiMobileLinkOK_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndWiFiMobileLinkOK_OnClose)
EVENT_ITEM(NVTEVT_WIFI_AUTHORIZED_OK,UIMenuWndWiFiMobileLinkOK_Authorized_OK)
EVENT_ITEM(NVTEVT_WIFI_EXE_PHOTO_CAPTURE,UIMenuWndWiFiMobileLinkOK_OnExePhotoCapture)
EVENT_ITEM(NVTEVT_WIFI_EXE_PHOTO_SIZE,UIMenuWndWiFiMobileLinkOK_OnExeSetPhotoSize)
EVENT_ITEM(NVTEVT_UPDATE_INFO,UIMenuWndWiFiMobileLinkOK_OnUpdateInfo)

EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_REC,UIMenuWndWiFiMobileLinkOK_OnExeMovieRec)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_REC_SIZE,UIMenuWndWiFiMobileLinkOK_OnExeSetMovieRecSize)
EVENT_ITEM(NVTEVT_WIFI_EXE_CYCLIC_REC,UIMenuWndWiFiMobileLinkOK_OnExeCyclicRec)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_HDR,UIMenuWndWiFiMobileLinkOK_OnExeSetMovieHDR)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_EV,UIMenuWndWiFiMobileLinkOK_OnExeSetMovieEV)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOTION_DET,UIMenuWndWiFiMobileLinkOK_OnExeSetMotionDet)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_AUDIO,UIMenuWndWiFiMobileLinkOK_OnExeSetMovieAudio)
EVENT_ITEM(NVTEVT_WIFI_EXE_DATEIMPRINT,UIMenuWndWiFiMobileLinkOK_OnExeSetMovieDateImprint)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_LIVEVIEW_SIZE, UIMenuWndWiFiMobileLinkOK_OnExeSetMovieLiveviewSize)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_GSENSOR_SENS, UIMenuWndWiFiMobileLinkOK_OnExeSetMovieGSesnorSensitivity)
EVENT_ITEM(NVTEVT_WIFI_EXE_SET_AUTO_RECORDING, UIMenuWndWiFiMobileLinkOK_OnExeSetAutoRecording)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_REC_BITRATE, UIMenuWndWiFiMobileLinkOK_OnExeSetMovieRecBitRate)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_LIVEVIEW_BITRATE, UIMenuWndWiFiMobileLinkOK_OnExeSetMovieLiveviewBitRate)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_LIVEVIEW_START, UIMenuWndWiFiMobileLinkOK_OnExeMovieLiveviewStart)
EVENT_ITEM(NVTEVT_WIFI_EXE_MOVIE_TRIGGER_RAWENC, UIMenuWndWiFiMobileLinkOK_OnExeTriggerMovieRawEnc)

EVENT_ITEM(NVTEVT_WIFI_EXE_MODE,UIMenuWndWiFiMobileLinkOK_OnExeModeChange)
EVENT_ITEM(NVTEVT_WIFI_EXE_SET_SSID,UIMenuWndWiFiMobileLinkOK_OnExeSetSSID)
EVENT_ITEM(NVTEVT_WIFI_EXE_SET_PASSPHRASE,UIMenuWndWiFiMobileLinkOK_OnExeSetPassphrase)
EVENT_ITEM(NVTEVT_WIFI_EXE_SET_DATE,UIMenuWndWiFiMobileLinkOK_OnExeDate)
EVENT_ITEM(NVTEVT_WIFI_EXE_SET_TIME,UIMenuWndWiFiMobileLinkOK_OnExeTime)
EVENT_ITEM(NVTEVT_WIFI_EXE_POWEROFF,UIMenuWndWiFiMobileLinkOK_OnExePoweroff)
EVENT_ITEM(NVTEVT_WIFI_EXE_LANGUAGE,UIMenuWndWiFiMobileLinkOK_OnExeLanguage)
EVENT_ITEM(NVTEVT_WIFI_EXE_TVFORMAT,UIMenuWndWiFiMobileLinkOK_OnExeTV)
EVENT_ITEM(NVTEVT_WIFI_EXE_FORMAT,UIMenuWndWiFiMobileLinkOK_OnExeFormat)
EVENT_ITEM(NVTEVT_WIFI_EXE_SYSRESET,UIMenuWndWiFiMobileLinkOK_OnExeSysReset)
EVENT_ITEM(NVTEVT_WIFI_EXE_FWUPDATE,UIMenuWndWiFiMobileLinkOK_OnExeFWUpdate)
EVENT_ITEM(NVTEVT_WIFI_EXE_RECONNECT,UIMenuWndWiFiMobileLinkOK_OnExeReconnect)
EVENT_ITEM(NVTEVT_WIFI_EXE_SAVEMENU,UIMenuWndWiFiMobileLinkOK_OnExeSaveMenu)
EVENT_ITEM(NVTEVT_WIFI_EXE_REMOVE_USER,UIMenuWndWiFiMobileLinkOK_OnExeRemoveUser)
EVENT_ITEM(NVTEVT_WIFI_EXE_PIP_STYLE,UIMenuWndWiFiMobileLinkOK_OnExePipStyle)
EVENT_ITEM(NVTEVT_WIFI_EXE_SEND_SSID_PASSPHRASE,UIMenuWndWiFiMobileLinkOK_OnExeSendSSIDPassphrase)
EVENT_ITEM(NVTEVT_WIFI_EXE_SET_WIFI_CONNECT_MODE,UIMenuWndWiFiMobileLinkOK_OnExeSetWiFiConnectMode)

EVENT_ITEM(NVTEVT_BACKGROUND_DONE,UIMenuWndWiFiMobileLinkOK_OnBackgroundDone)

EVENT_ITEM(NVTEVT_CB_MOVIE_OVERTIME,UIMenuWndWiFiMobileLinkOK_OnMovieFull) // the same handling as storage full (may need to show special message)
EVENT_ITEM(NVTEVT_CB_MOVIE_FULL,UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_LOOPREC_FULL,UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_WR_ERROR,UIMenuWndWiFiMobileLinkOK_OnMovieWrError)
EVENT_ITEM(NVTEVT_CB_MOVIE_SLOW,UIMenuWndWiFiMobileLinkOK_OnStorageSlow)
EVENT_ITEM(NVTEVT_CB_MOVIE_DELETE_FILES,UIMenuWndWiFiMobileLinkOK_OnDeleteFiles)
EVENT_ITEM(NVTEVT_CB_MOVIE_DELETE_RO_FILES,UIMenuWndWiFiMobileLinkOK_OnDeleteROFiles)
EVENT_ITEM(NVTEVT_CB_MOVIE_REC_ONE_SEC,UIMenuWndWiFiMobileLinkOK_OnMovieOneSec)
EVENT_ITEM(NVTEVT_CB_RAWENC_JPG_OK, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB)
EVENT_ITEM(NVTEVT_CB_RAWENC_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_WRITE_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_DCF_FULL, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_BATTERY_LOW,UIMenuWndWiFiMobileLinkOK_OnBatteryLow)
EVENT_ITEM(NVTEVT_WIFI_DEAUTHENTICATED,UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndWiFiMobileLinkOK_OnTimer)
EVENT_ITEM(NVTEVT_WIFI_STATE,UIMenuWndWiFiModuleLinkOK_OnWiFiState)
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
EVENT_ITEM(NVTEVT_WIFI_EXE_HEARTBEAT, UIMenuWndWiFiMobileLinkOK_OnExeHB)
EVENT_ITEM(NVTEVT_WIFI_EXE_APP_SESSION_CLOSE,UIMenuWndWiFiMobileLinkOK_OnAppSessionClose)
#endif
//#NT#2016/03/23#Isiah Chang -end

//drh 20170922 
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndWiFiModuleLinkOK_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndWiFiModuleLinkOK_OnKeyDown)


EVENT_END
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
static UINT32 uiWifiAppHBCnt  = 0;
static BOOL   bWifiAppHBStart = FALSE;
#endif
//#NT#2016/03/23#Isiah Chang -end
extern char gLastMacAddr[];
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    static char buf1[32] = {0}, buf2[32] = {0} ;

#if 0
    sprintf(buf1,"WiFi Connected");
    UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl,STATIC_VALUE,Txt_Pointer(buf1));
    sprintf(StringMacBuf," MAC : %s",UINet_GetConnectedMAC());
    UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringMacBuf));

    sprintf(buf2,"Press OK to Disconnect");
    UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl, 0, BTNITM_STRID, Txt_Pointer(buf2));
#endif

    //#NT#2016/03/23#Isiah Chang -begin
    //#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
    uiWifiAppHBCnt  = 0;
    bWifiAppHBStart = FALSE;
//#NT#2016/11/15#Isiah Chang -begin
//#NT#Ignore command except app_startup command is received..
    WifiApp_SetSessionCloseSts(FALSE);
//#NT#2016/11/15#Isiah Chang -end

    if (gUIMenuWndWiFiHeartBeatTimerID==NULL_TIMER)
    {
        gUIMenuWndWiFiHeartBeatTimerID = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
    }
#endif
    //#NT#2016/03/23#Isiah Chang -end

    if (gUIMenuWndWiFiMotionDetTimerID==NULL_TIMER)
    {
        gUIMenuWndWiFiMotionDetTimerID = GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_05SEC_TIMER, CONTINUE);
    }
    //make sure, connec to RTSP mode
    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
    }

    WifiCmd_ReceiveCmd(TRUE);
	SysSetFlag(FL_WIFI_Connect,TRUE);
	FlowWifiMovie_UpdateIcons(TRUE);//drh 20170915
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
    #if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
    if (gUIMenuWndWiFiHeartBeatTimerID != NULL_TIMER)
    {
        GxTimer_StopTimer(&gUIMenuWndWiFiHeartBeatTimerID);
    }
    #else
    WifiCmd_ReceiveCmd(FALSE);
    #endif
//#NT#2016/03/23#Isiah Chang -end
    if (gUIMenuWndWiFiMotionDetTimerID!=NULL_TIMER)
    {
        GxTimer_StopTimer(&gUIMenuWndWiFiMotionDetTimerID);
    }

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 bNewUser = 0 ;
    if(paramNum)
        bNewUser = paramArray[0];

#if 0
    sprintf(StringMacBuf," MAC : %s",UINet_GetConnectedMAC());
    UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringMacBuf));
#endif

    if(bNewUser)
    {
        //delay 500 ms,disconnect last user and
        //in window,use GxTimer replace Timer Delay,it would occupat UI task
        GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DISCONNECT_LAST_TIMER, ONE_SHOT);
    }
    //make sure, connec to RTSP mode
    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
    }

    return NVTEVT_CONSUME;
}


INT32 UIMenuWndWiFiMobileLinkOK_OnExePhotoCapture(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiPhoto_OnExePhotoCapture(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnUpdateInfo(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiPhoto_OnUpdateInfo(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetPhotoSize(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiPhoto_OnExeSetPhotoSize(pCtrl, paramNum, paramArray);
}

/************************************************************************/
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeMovieRec(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieRecSize(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieRecSize(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeCyclicRec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetCyclicRec(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieHDR(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetHDR(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieEV(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieEV(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMotionDet(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMotionDet(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieAudio(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieAudio(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieDateImprint(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieDateImprint(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieLiveviewSize(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieLiveviewSize(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieGSesnorSensitivity(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieGSesnorSensitivity(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetAutoRecording(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetAutoRecording(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieRecBitRate(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieRecBitRate(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetMovieLiveviewBitRate(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeSetMovieLiveviewBitRate(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieLiveviewStart(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeMovieLiveviewStart(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeTriggerMovieRawEnc(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    return UIFlowWndWiFiMovie_OnExeMovieTriggerRawEnc(pCtrl, paramNum, paramArray);
}

/************************************************************************/


INT32 UIMenuWndWiFiMobileLinkOK_OnExeModeChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 par = 0;
    INT32 curMode = System_GetState(SYS_STATE_CURRMODE);
    if(paramNum>0)
    {
        par=paramArray[0];
    }

    switch(par)
    {
        case WIFI_APP_MODE_PHOTO:
            if(curMode != PRIMARY_MODE_PHOTO)
                Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PHOTO);
            else
                WifiCmd_Done(WIFIFLAG_MODE_DONE,WIFIAPP_RET_OK);
        break;
        case WIFI_APP_MODE_MOVIE:
            if(curMode != PRIMARY_MODE_MOVIE)
                Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
            else
                WifiCmd_Done(WIFIFLAG_MODE_DONE,WIFIAPP_RET_OK);
        break;
        case WIFI_APP_MODE_PLAYBACK:
            if(curMode != PRIMARY_MODE_PLAYBACK)
                Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);
            else
                WifiCmd_Done(WIFIFLAG_MODE_DONE,WIFIAPP_RET_OK);
        break;
        default:
            WifiCmd_Done(WIFIFLAG_MODE_DONE,WIFIAPP_RET_PAR_ERR);
        break;
    }

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetSSID(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %s\r\n",__FUNCTION__,paramArray[0]);
    char *Data = 0;
    char SSID[WIFI_PAR_STR_LEN] ={0};
    if(paramNum)
    {
        Data = (char *)paramArray[0];
        UIMenuWndWiFiMobileLinkOKTraceMsg("%d\r\n",strlen(Data));

        if (1 == sscanf(Data, "%[^\0]", SSID))
        {
            Ux_SendEvent(0,NVTEVT_EXE_WIFI_SET_SSID, 1, SSID);
        }
        WifiCmd_UnlockString(Data);
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetPassphrase(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %s\r\n",__FUNCTION__,paramArray[0]);
    char *Data = 0;
    char Passphrase[WIFI_PAR_STR_LEN] ={0};

    if(paramNum)
    {
        Data = (char *)paramArray[0];
        UIMenuWndWiFiMobileLinkOKTraceMsg("%d\r\n",strlen(Data));

        if (1 == sscanf(Data, "%[^\0]", Passphrase))
        {
            if(strlen(Passphrase) >= 8)
            {
                Ux_SendEvent(0,NVTEVT_EXE_WIFI_SET_PASSPHRASE, 1, Passphrase);
            }
            else
            {
                debug_err(("Passphrase length illegal!\r\n"));
            }
        }
        WifiCmd_UnlockString(Data);
    }

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeDate(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    char *Data = 0;
    UINT32 uiYear, uiMonth, uiDay;
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %s\r\n",__FUNCTION__,paramArray[0]);
    if(paramNum)
    {
        Data = (char *)paramArray[0];
        UIMenuWndWiFiMobileLinkOKTraceMsg("%d\r\n",strlen(Data));

        if (3 == sscanf(Data, "%d-%d-%d;", &uiYear, &uiMonth, &uiDay))
        {
            WifiCmd_UnlockString(Data);//setDate cost time,unlock string before rtc_setDate
            UIMenuWndWiFiMobileLinkOKTraceMsg("Y:%d, M:%d, D:%d\r\n", uiYear, uiMonth, uiDay);
            rtc_setDate(uiYear, uiMonth, uiDay);
            rtc_triggerCSET();
        }
        else
        {
            WifiCmd_UnlockString(Data);
        }
    }

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeTime(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    char *Data = 0;
    UINT32 uiHour, uiMin, uiSec;

    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %s\r\n",__FUNCTION__,paramArray[0]);
    if(paramNum)
    {
        Data = (char *)paramArray[0];
        UIMenuWndWiFiMobileLinkOKTraceMsg("%d\r\n",strlen(Data));

        if (3 == sscanf(Data, "%d:%d:%d;", &uiHour, &uiMin, &uiSec))
        {
            WifiCmd_UnlockString(Data);//setTime cost time,unlock string before rtc_setTime
            UIMenuWndWiFiMobileLinkOKTraceMsg("hh:%d, mm:%d, dd:%d\r\n", uiHour, uiMin, uiSec);
            rtc_setTime(uiHour, uiMin, uiSec);
            rtc_triggerCSET();
        }
        else
        {
            WifiCmd_UnlockString(Data);
        }
    }

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExePoweroff(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    UINT32 Data = 0;
    if(paramNum)
        Data = paramArray[0];
    Ux_SendEvent(0,NVTEVT_EXE_POWEROFF, 1, Data);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeLanguage(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    UINT32 Data = 0;
    if(paramNum)
        Data = paramArray[0];
    Ux_SendEvent(0,NVTEVT_EXE_LANGUAGE, 1, Data);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeTV(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    UINT32 Data = 0;
    if(paramNum)
        Data = paramArray[0];

    #if TV_FUNC
    Ux_SendEvent(0,NVTEVT_EXE_TVFORMAT, 1, Data);
    #else
    debug_err(("TV function not support!\r\n"));
    #endif

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeFormat(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);
    UINT32 Data = 0;
    if(paramNum)
        Data = paramArray[0];
    if(Data == 0)
    {
        BKG_PostEvent(NVTEVT_BKW_FORMAT_NAND);
    }
    else if(Data==1)
    {
        if(UI_GetData(FL_CardStatus) == CARD_REMOVED)
        {
            UIMenuWndWiFiMobileLinkOKErrMsg("card removed\r\n");
            WifiCmd_Done(WIFIFLAG_FORMAT_DONE,E_NOEXS);

        }
        else if(UIStorageCheck(STORAGE_CHECK_LOCKED, NULL) == TRUE)
        {
            UIMenuWndWiFiMobileLinkOKErrMsg("card lock\r\n");
            WifiCmd_Done(WIFIFLAG_FORMAT_DONE,E_OBJ);
        }
        else
        {
            BKG_PostEvent(NVTEVT_BKW_FORMAT_CARD);
        }
    }
    else
    {
        UIMenuWndWiFiMobileLinkOKErrMsg("err param\r\n");
        WifiCmd_Done(WIFIFLAG_FORMAT_DONE,E_PAR);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSysReset(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    Ux_SendEvent(0,NVTEVT_EXE_SYSRESET,0);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeFWUpdate(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    BKG_PostEvent(NVTEVT_BKW_FW_UPDATE);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeReconnect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);

    Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
    Ux_SendEvent(0,NVTEVT_EXE_WIFI_START, 0);
    Ux_CloseWindow(pCtrl,0);

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeSaveMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    Save_MenuInfo();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeRemoveUser(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    UINet_RemoveUser();
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExePipStyle(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    UINT32 Data = 0;
    if(paramNum)
        Data = paramArray[0];

    Ux_SendEvent(0,NVTEVT_EXE_WIFI_SET_PIP_STYLE, 1, Data);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeSendSSIDPassphrase(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    UINT32 Data = 0;
    if(paramNum)
        Data = paramArray[0];

    Ux_SendEvent(0,NVTEVT_EXE_WIFI_SEND_SSID_PASSPHRASE, 1, Data);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeSetWiFiConnectMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    UINT32 Data = 0;
    if(paramNum)
        Data = paramArray[0];

    Ux_SendEvent(0,NVTEVT_EXE_WIFI_MODE, 1, Data);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVTEVT event;
    UINT32 status;

    event = paramArray[ONDONE_PARAM_INDEX_CMD];
    status = paramArray[ONDONE_PARAM_INDEX_RET];
    debug_err(("%s event = 0x%x, status=%d\r\n",__FUNCTION__, event, status));

    switch(event)
    {
        case NVTEVT_BKW_FORMAT_CARD:
        {
            WifiCmd_Done(WIFIFLAG_FORMAT_DONE,WIFIAPP_RET_OK);
            //Rsvd
            break;
        }

        case NVTEVT_BKW_FORMAT_NAND:
        {
            WifiCmd_Done(WIFIFLAG_FORMAT_DONE,WIFIAPP_RET_OK);
            //Rsvd
            break;
        }

        case NVTEVT_BKW_FW_UPDATE:
        {
            if(status)
            {
                debug_err(("%s:update FW fail %d\r\n",__FUNCTION__,status));
                WifiCmd_Done(WIFIFLAG_UPDATE_DONE,status+WIFIAPP_RET_FW_OFFSET);
            }
            else
            {
                WifiCmd_Done(WIFIFLAG_UPDATE_DONE,WIFIAPP_RET_OK);
                Delay_DelayMs(2000);
                // Should power off immediatelly
                System_PowerOff(SYS_POWEROFF_NORMAL);
            }
            break;
        }

        default:
            debug_err(("%s:Unknown event 0x%x\r\n",__FUNCTION__, event));
            break;
    }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnMovieFull(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnMovieWrError(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnStorageSlow(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnDeleteFiles(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnDeleteFiles(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnDeleteROFiles(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnDeleteROFiles(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	debug_msg("^G MobileLinkOK_OnMovieOneSec %d \r\n",paramArray[0]);
    return UIFlowWndWiFiMovie_OnMovieOneSec(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnMovieRawEncJpgOKCB(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnMovieRawEncErr(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n",__FUNCTION__);
    WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS,WIFIAPP_RET_BATTERY_LOW);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
    Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
#else
    sprintf(StringMacBuf,"No connect");
    //UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringMacBuf));
#if(_NETWORK_ == _NETWORK_SDIO_EVB_WIFI_ || _NETWORK_ == _NETWORK_SDIO_EVB_WIFI_NVT_ || _NETWORK_ == _NETWORK_SDIO_EVB_WIFI_BRCM_)
    UINet_CliReConnect();
#endif
#endif
//#NT#2016/03/23#Isiah Chang -end
    return NVTEVT_CONSUME;

    //Ux_CloseWindow(pCtrl,0);

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;
    uiEvent = paramNum ? paramArray[0] : 0;
	//debug_msg("drh UINet_GetStationConnected %d \r\n",UINet_GetStationConnected());//drh 20170922 
    switch(uiEvent)
    {
        case NVTEVT_DISCONNECT_LAST_TIMER:
            UINet_AddACLTable();
            return NVTEVT_CONSUME;
        case NVTEVT_DELAY_CLOSE_TIMER:
            // Return to SSID and Password page.
            Ux_CloseWindow(&UIMenuWndWiFiMobileLinkOKCtrl,0);
            return NVTEVT_CONSUME;

        //#NT#2016/03/23#Isiah Chang -begin
        //#NT#add new Wi-Fi UI flow.
        #if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
        case NVTEVT_1SEC_TIMER:
        {
            if (bWifiAppHBStart)
            {
                uiWifiAppHBCnt++;

                if (uiWifiAppHBCnt >= 10)
                {
                    debug_err(("HB timeout!!\r\n"));
                    uiWifiAppHBCnt = 0;
                    bWifiAppHBStart = FALSE;
                    Ux_PostEvent(NVTEVT_WIFI_EXE_APP_SESSION_CLOSE, 0);
                }
            }

            return NVTEVT_CONSUME;
        }
        #endif
        //#NT#2016/03/23#Isiah Chang -end

        default:
            return UIFlowWndWiFiMovie_OnTimer(pCtrl, paramNum, paramArray);
    }
}

INT32 UIMenuWndWiFiModuleLinkOK_OnWiFiState(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum==2)
    {
        if(UI_GetData(FL_NetWorkMode) == NET_AP_MODE)
        {
            debug_msg("^G drh ap  state %d result %d\r\n",paramArray[0],paramArray[1]);
            UINT32 state = paramArray[0];
            INT32 result = paramArray[1];
            // wifi phase status
            if(state == NET_STATE_WIFI_CB)
            {
                if(result == NVT_WIFI_AP_READY)
                {
                    debug_msg("^G drh ap mode OK\r\n");
                }
                else if(result == NVT_WIFI_LINK_STATUS_CONNECTED)
                {
                	SysSetFlag(FL_WIFI_Connect, TRUE);
                	FlowWifiMovie_DrawWifi(&UIMenuWndWiFiMobileLinkOK_Status_WifiStatusCtrl);//drh 20170922	
                    debug_msg("^G drh ap NVT_WIFI_LINK_STATUS_CONNECTED\r\n");
                }
				else if(result == NVT_WIFI_LINK_STATUS_DISCONNECTED)
				{
					debug_msg("^G drh ap NVT_WIFI_LINK_STATUS_DISCONNECTED\r\n");
				}
				else if(result == NVT_WIFI_LINK_STATUS_DEAUTHENTICATED)
				{
					SysSetFlag(FL_WIFI_Connect, FALSE);
					FlowWifiMovie_DrawWifi(&UIMenuWndWiFiMobileLinkOK_Status_WifiStatusCtrl);	//drh 20170922
					debug_msg("^G drh ap NVT_WIFI_LINK_STATUS_DEAUTHENTICATED\r\n");
				}

            }
        }
        else // station mode
        {
            debug_msg("sta  state %d result %d\r\n",paramArray[0],paramArray[1]);
            UINT32 state = paramArray[0];
            INT32 result = paramArray[1];

            if(state == NET_STATE_DHCP_START)
            {
                if(result == 0)
                {
                    debug_msg("station mode OK\r\n");
                }
                else
                {
                    debug_msg("DHCP fail or wifi module failed\r\n");
                }
            }
            else if (state == NET_STATE_WIFI_CB)
            {
                if (result == NVT_WIFI_LINK_STATUS_CONNECTED)
                {
					debug_msg("^G drh NVT_WIFI_LINK_STATUS_CONNECTED\r\n");
                }
                else
                {
					debug_msg("^G drh NVT_WIFI_LINK_STATUS_DISCONNECTED\r\n");
                }
            }
            else if(state == NET_STATE_WIFI_CONNECTING)
            {
                if(result == NET_CONNECTING_TIMEOUT)
                {
                    debug_msg("wifi module failed\r\n");
                }
            }
        }
    }
    else
    {
        debug_msg("err paramNum %d\r\n",paramNum);
    }
    return NVTEVT_CONSUME;
}


//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
INT32 UIMenuWndWiFiMobileLinkOK_OnExeHB(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    CHAR heartbeat[] = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<Function>\n<Cmd>3016</Cmd>\n<Status>0</Status>\n</Function>\n";
    int  sendsize = 0;

    UIMenuWndWiFiMobileLinkOKTraceMsg("%s %d\r\n",__FUNCTION__,paramArray[0]);

    sendsize = sizeof(heartbeat);
    UserSocket_Send(heartbeat, &sendsize);

    bWifiAppHBStart = TRUE;
    uiWifiAppHBCnt = 0;      // reset HB count

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnAppSessionClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    debug_msg("Close Wi-Fi window\r\n");

//#NT#2016/11/15#Isiah Chang -begin
//#NT#Ignore command except app_startup command is received..
    WifiApp_SetSessionCloseSts(TRUE);
//#NT#2016/11/15#Isiah Chang -end

    Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
    //Ux_PostEvent(NVTEVT_KEY_SELECT, 1, NVTEVT_KEY_PRESS);
    return NVTEVT_CONSUME;
}
#endif

INT32 UIMenuWndWiFiModuleLinkOK_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiKeyAct;
	static BOOL bKey_Continue = FALSE;
	static UINT32 bKey_Continue_Count = 0;
	
    uiKeyAct = paramArray[0];


	switch (uiKeyAct)
    {
      	case NVTEVT_KEY_PRESS:
			bKey_Continue = FALSE;
			bKey_Continue_Count = 0;
			break;

		 case NVTEVT_KEY_CONTINUE:
			bKey_Continue = TRUE;
			bKey_Continue_Count ++ ;
			if(bKey_Continue_Count == 1) //the first time
			{
				//filp
			}
			break;

		 case NVTEVT_KEY_RELEASE:
			if(bKey_Continue == FALSE){	
				;//return UIFlowWndMovie_OnExeZoomIn(pCtrl,paramNum,paramArray);
			}
			else if (bKey_Continue == TRUE){
				//return UIFlowWndMovie_OnExeZoomIn(pCtrl,paramNum,paramArray);
			}
			break;
	}
	
    return NVTEVT_CONSUME;
    //return UIFlowWndMovie_OnExeZoomIn(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiModuleLinkOK_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiKeyAct;
	static BOOL bKey_Continue = FALSE;
	static INT32 bKey_Continue_Count = -1;
	
    uiKeyAct = paramArray[0];
		
	switch (uiKeyAct)
    {
      	case NVTEVT_KEY_PRESS:
			bKey_Continue = FALSE;
			bKey_Continue_Count = 0;
			break;

		 case NVTEVT_KEY_CONTINUE:
			bKey_Continue = TRUE;
			if(bKey_Continue_Count < 0)	break;
				bKey_Continue_Count ++ ;
			if(bKey_Continue_Count == 1) //the first time
			{
				Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, PRIMARY_MODE_MOVIE,SYS_SUBMODE_NORMAL);//drh 20170922
			}
			break;

		 case NVTEVT_KEY_RELEASE:
			if(bKey_Continue == FALSE){	
				;//return UIFlowWndMovie_OnExeZoomOut(pCtrl,paramNum,paramArray); //drh change 20170829
			}
			else if(bKey_Continue == TRUE){
				//return UIFlowWndMovie_OnExeZoomOut(pCtrl,paramNum,paramArray); //drh change 20170829
			}
			else{
				;
			}
			bKey_Continue_Count = -1;
			break;
	}
    return NVTEVT_CONSUME;
    //return UIFlowWndMovie_OnExeZoomOut(pCtrl, paramNum, paramArray);
}


//----------------------UIMenuWndWiFiMobileLinkOK_Static_cameraCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_camera)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_CyclicRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_CyclicRec)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_MotionDetCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_MotionDet)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_batteryCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_battery)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_YMD_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_YMD_Static)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_HMS_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_HMS_Static)
EVENT_END

//---------------------UIMenuWndWiFiMobileLinkOK_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_StorageCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Storage)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_timeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_time)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_resolutionCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_resolution)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Zoom_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Zoom_Static)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusICN_EVCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusICN_EV)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_HDRCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_HDR)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StaticIcon_PIMCCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticIcon_PIMC)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_WifiStatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_WifiStatus)
EVENT_END
#endif
