#ifndef _UIAPPUSBPRINT_H_
#define _UIAPPUSBPRINT_H_

#include "Debug.h"
#include "UIFramework.h"
#include "NVTUserCommand.h"
#include "UIPrinterObj.h"


typedef enum
{
    NVTEVT_EXE_DATEON = NVTEVT_PRINT_MAX + 1,
    NVTEVT_EXE_PAPERSIZE,
    NVTEVT_EXE_LAYOUT,
    NVTEVT_EXE_PRT_QUALITY,
    NVTEVT_EXE_PRT_NAMEPRINT,
#if 0 //move to UIAppUsbEvent.h
    NVTEVT_CB_PRINT_INITDONE,
    NVTEVT_CB_PRINT_INITFAILED,
    NVTEVT_CB_PRINT_OK,
    NVTEVT_CB_PRINT_FAIL,
    NVTEVT_CB_PRINT_NOINK,
    NVTEVT_CB_PRINT_PAPEROUT,
    NVTEVT_CB_PRINT_CLOSESESSION,
    NVTEVT_CB_PRINT_NOTIFYJOB,
    NVTEVT_CB_PRINT_RESULTS
#endif
}CUSTOM_PRINT_EVENT;


extern void     AppInit_ModeUSBSIDC(void);
extern void     DevCtrl_ModeUSBSIDC(void);
extern void     DevCtrl_ModeUSBSIDC_Remove(void);

extern VControl CustomPrintObjCtrl;


#if 0 //move to UIAppUsbEvent.h
typedef enum
{
    PRINT_RESULTS_PRINT_OK = 0,
    PRINT_RESULTS_PRINT_WARN,
    PRINT_RESULTS_PRINT_ERROR,
    PRINT_RESULTS_PAPER_WARN,
    PRINT_RESULTS_PAPER_ERROR,
    PRINT_RESULTS_INK_WARN,
    PRINT_RESULTS_INK_ERROR,
    PRINT_RESULTS_HW_WARN,
    PRINT_RESULTS_HW_ERROR,
    PRINT_RESULTS_FILE_WARN,
    PRINT_RESULTS_FILE_ERROR,
    PRINT_RESULTS_PAPER_EMPTY, //11
    PRINT_RESULTS_PAPER_JAM,
    PRINT_RESULTS_PAPER_LOAD,
    PRINT_RESULTS_PAPER_NEAR_EMPTY,
    PRINT_RESULTS_PAPER_NOT_SUPPORT,
    PRINT_RESULTS_INK_LOW,
    PRINT_RESULTS_INK_EMPTY,
    PRINT_RESULTS_PTR_ERROR,
    PRINT_RESULTS_PTR_UNAVAILABLE,
    PRINT_RESULTS_PTR_OPEN,
    PRINT_RESULTS_PTR_HEAD,//21
    PRINT_RESULTS_PTR_INK,
    PRINT_RESULTS_PTR_CART,
    PRINT_RESULTS_PRINT_QUANTITY,
    PRINT_RESULTS_PRT_CLOSEESSION,
    PRINT_RESULTS_MAX
}PRINT_RESULTS_SET;
#endif


#endif //_UIAPPUSBPRINT_H_
