//This source code is generated by UI Designer Studio.

#ifndef DIALOGWARN_H
#define DIALOGWARN_H

#include "UIFramework.h"

extern VControl DialogWarnCtrl;//Panel type

extern VControl WarnGrayBGCtrl;//Static type

extern VControl WarnTransparentBGCtrl;//Static type

extern VControl WarnUpperStrCtrl;//Static type

extern VControl WarnCenterStrCtrl;//Static type

//---------------------DialogWarnCtrl User Export---------------------------
typedef enum {
    WARN_REMOVE_USB = 0,
    WARN_CONNECT_FAIL,
    WARN_UNKNOWN_FILE,
    WARN_NO_PICTURE,
    WARN_LENS_ERROR,
    WARN_CARD_ERROR,
    WARN_BUILT_IN_MEMORY_ERROR,
    WARN_CARD_UNFORMAT,
    WARN_WRITE_PROTECT,
    WARN_CARD_FULL,
    WARN_MEM_FULL,
    WARN_FILE_PROTECT,
    WARN_DEL_PROTECT,
    WARN_BATT_EMPTY,
    WARN_PAN_ERROR,
    WARN_COPY_CARD_FULL,
    WARN_COPY_CARD_PROTECT,
    WARN_COPY_NO_PICTURE,
    WRN_FW_UPDATE_COMPLETE,
    //#NT#2011/01/03#Photon Lin -begin
    //#NT#Add slow media
    WARN_RECORD_SLOW_MEDIA,
    //#NT#2011/01/03#Photon Lin -end
    WRN_FW_UPDATING,
    WRN_FW_CHECK,
    //#NT#2011/01/12#Ben Wang -begin
    WRN_NOT_DETECT_REDEYE,
    //#NT#2011/01/12#Ben Wang -end
    WRN_EXCEED_MAX_FOLDER,
    //#NT#2011/01/26#Ben Wang -begin
    WRN_TOO_MANY_PIC,
    //#NT#2011/01/26#Ben Wang -end
    WARN_TYPE_MAX
}WARN_TYPE;

typedef enum {
    WARN_ALWAYS = WARN_TYPE_MAX + 1,
    WARN_2_SEC,
    WARN_TIME_MAX
}WARN_TIME;

#endif
