//This source code is generated by UI Designer Studio.

#ifndef FLOWPLAY_H
#define FLOWPLAY_H

#include "UIFramework.h"

extern VControl FlowPlayCtrl;//Panel type 

extern VControl PanelDisp2Ctrl;//Panel type 

extern VControl PlayModeCtrl;//Static type 

extern VControl PlayMediaTypeCtrl;//Static type 

extern VControl LockCtrl;//Static type 

extern VControl DpofCtrl;//Static type 

extern VControl PlayVMCtrl;//Static type 

extern VControl FileNameCtrl;//Static type 

extern VControl PlayCardCtrl;//Static type 

extern VControl PlaySizeCtrl;//Static type 

extern VControl PlayWBCtrl;//Static type 

extern VControl PlayISOCtrl;//Static type 

extern VControl PlayDateTimeCtrl;//Static type 

extern VControl PlayEVCtrl;//Static type 

extern VControl FNumberCtrl;//Static type 

extern VControl Exp_TimeCtrl;//Static type 

extern VControl PlayFileNumCtrl;//Static type 

extern VControl PlayMovieIconCtrl;//Static type 

extern VControl PlayMovieTime1Ctrl;//Static type 

extern VControl PlayMovieTime2Ctrl;//Static type 

extern VControl PlayZoomWinCtrl;//Static type 

extern VControl HDRCtrl;//Static type 

extern VControl PlayOKIconCtrl;//Static type 

extern VControl Disp2ThirdLineCtrl;//Static type 

//---------------------FlowPlayCtrl User Export---------------------------
#endif
