//This source code is generated by UI Designer Studio.

#ifndef FLOWPANCAP_H
#define FLOWPANCAP_H

#include "UIFramework.h"

extern VControl FlowPanCapCtrl;//Panel type 

extern VControl Indicate_IconCtrl;//Status type 

typedef enum
{
Indicate_Icon_ICONID_PANARAMA_1L1,
Indicate_Icon_ICONID_PANARAMA_1L2,
Indicate_Icon_ICONID_PANARAMA_1L,
Indicate_Icon_ICONID_PANARAMA_1R1,
Indicate_Icon_ICONID_PANARAMA_1R2,
Indicate_Icon_ICONID_PANARAMA_1R,
Indicate_Icon_MAX
}Indicate_Icon_Setting;

extern VControl Indicate_Icon_2Ctrl;//Status type 

typedef enum
{
Indicate_Icon_2_ICONID_PANARAMA_L,
Indicate_Icon_2_ICONID_PANARAMA_R,
Indicate_Icon_2_MAX
}Indicate_Icon_2_Setting;

extern VControl Indicate_LineCtrl;//StatusGraph type 

typedef enum
{
Indicate_Line_Normal,
Indicate_Line_MAX
}Indicate_Line_Setting;

extern VControl Destination_L2RCtrl;//Status type 

typedef enum
{
Destination_L2R_ICONID_PAN_3_1,
Destination_L2R_ICONID_PAN_3_1_MATCH,
Destination_L2R_MAX
}Destination_L2R_Setting;

extern VControl Destination_R2LCtrl;//Status type 

typedef enum
{
Destination_R2L_ICONID_PAN_3_1,
Destination_R2L_ICONID_PAN_3_1_MATCH,
Destination_R2L_MAX
}Destination_R2L_Setting;

extern VControl Indicate_L2RCtrl;//Status type 

typedef enum
{
Indicate_L2R_ICONID_PAN_1_2,
Indicate_L2R_ICONID_PAN_1_1,
Indicate_L2R_ICONID_PAN_4_1,
Indicate_L2R_ICONID_PAN_4_1_MATCH,
Indicate_L2R_MAX
}Indicate_L2R_Setting;

extern VControl Indicate_R2LCtrl;//Status type 

typedef enum
{
Indicate_R2L_ICONID_PAN_2_2,
Indicate_R2L_ICONID_PAN_2_1,
Indicate_R2L_ICONID_PAN_4_1,
Indicate_R2L_ICONID_PAN_4_1_MATCH,
Indicate_R2L_MAX
}Indicate_R2L_Setting;

extern VControl PanCapSaveIconCtrl;//Status type 

typedef enum
{
PanCapSaveIcon_ICONID_WORK_GUIDE_SAVE,
PanCapSaveIcon_ICONID_WORK_GUIDE_SELECT_PANORAMA,
PanCapSaveIcon_MAX
}PanCapSaveIcon_Setting;

extern VControl PanCapCancelIconCtrl;//Status type 

typedef enum
{
PanCapCancelIcon_ICONID_WORK_GUIDE_CANCEL,
PanCapCancelIcon_MAX
}PanCapCancelIcon_Setting;

extern VControl PanCapPictNumberCtrl;//Static type 

extern VControl PanCapFocusFrmCtrl;//Status type 

typedef enum
{
PanCapFocusFrm_ICONID_AF_INDICATOR_NORMAL,
PanCapFocusFrm_ICONID_AF_INDICATOR,
PanCapFocusFrm_ICONID_AF_INDICATOR_FAIL,
PanCapFocusFrm_MAX
}PanCapFocusFrm_Setting;

extern VControl PanFnoCtrl;//Static type 

extern VControl PanShutterCtrl;//Static type 

//---------------------FlowPanCapCtrl User Export---------------------------
#define PANO_PIC_NUM_MIN            3

typedef enum
{
    PANCAP_UI_QUICKVIEW,
    PANCAP_UI_PREVIEWVIEW_ON,
    PANCAP_UI_PREVIEWVIEW_OFF,
    PANCAP_UI_PANL2RVIEW,
    PANCAP_UI_PANR2LVIEW,
    PANCAP_UI_PAN_CLOSE_LVIEW,
    PANCAP_UI_MAX
}PANCAP_UI_SETTING;

typedef enum
{
    FLOWPANCAP_CHILD_WND_NULL        = 0x00,
    FLOWPANCAP_CHILD_WND_MENU,
    FLOWPANCAP_CHILD_WND_DSCMODE,
    FLOWPANCAP_CHILD_WND_WRNSTORAGE,
    FLOWPANCAP_CHILD_WND_PANERROR,
    FLOWPANCAP_CHILD_WND_SETUPLANG,
    FLOWPANCAP_CHILD_WND_SETUPDATE
} FLOWPANCAP_CHILD_WND_MODE;


typedef struct _UIPanoramaConfig
{
    UINT32          uiDisplayHSize;         // Display window H-size
    UINT32          uiDisplayVSize;         // Display window V-size
    UINT32          uiDirIndex;             // Panorama direction index
    UINT32          uiGuideWidthPercent;    // Panorama guide image width portion, in unit of percentage
    UINT32          uiV1V2Blending;         // Video1 blending with Video2 operation
} UIPanoramaConfig;

typedef struct _FlowInfoTypePanCap
{
    BOOL                       isS1Press;
    BOOL                       isS2Press;
    BOOL                       isZoomInPressed;
    BOOL                       isZoomOutPressed;
    BOOL                       isFocusEnd;
    BOOL                       isStartCapture;
    BOOL                       isStartAuto;
    BOOL                       isStopNow;
    UINT32                     uiQviewTimerID;
    UINT32                     uiAFFailTimerID;
    UINT32                     uiCaptureTimerID;
    UINT32                     uiZoomDispTimerID;
    UINT32                     uiPicCnt;
    UINT32                     PictNumber;
    UINT8                      PictNumberStr[6];       //Picture number display string
    //#NT#2010/11/22#Lincy Lin -begin
    //#NT#
    UINT8                      Fno[6];
    UINT8                      Shutter[6];
    //#NT#2010/11/22#Lincy Lin -end
    UINT32                     uiPanDir;               //Direction of pan-capture
    UINT32                     uiWarnType;
    UINT32                     uiChildWnd;
} FlowInfoTypePanCap;
#endif
