//This source code is generated by UI Designer Studio.

#ifndef MENUDATETIME_H
#define MENUDATETIME_H

#include "UIFramework.h"

extern VControl MenuDatetimeCtrl;//Panel type 

extern VControl TextAMCtrl;//Static type 

extern VControl TextPMCtrl;//Static type 

extern VControl TextHMCtrl;//Static type 

extern VControl TextYMDCtrl;//Static type 

extern VControl TextMDYCtrl;//Static type 

extern VControl TextDMYCtrl;//Static type 

extern VControl DTTabCtrl;//Tab type 

typedef enum
{
DTTab_DTListFmt,
DTTab_DTListDateY,
DTTab_DTListDateM,
DTTab_DTListDateD,
DTTab_DTListTimeH,
DTTab_DTListTimeM,
DTTab_DTListTimeHR,
DTTab_MAX
}DTTab_Setting;

extern VControl DTListFmtCtrl;//List type 

typedef enum
{
DTListFmt_ICONID_TIME_SYSTEM1,
DTListFmt_ICONID_TIME_SYSTEM2,
DTListFmt_ICONID_TIME_SYSTEM3,
DTListFmt_MAX
}DTListFmt_Setting;

extern VControl DTListDateYCtrl;//List type 

typedef enum
{
DTListDateY_STRID_NULL,
DTListDateY_MAX
}DTListDateY_Setting;

extern VControl DTListDateMCtrl;//List type 

typedef enum
{
DTListDateM_STRID_NULL,
DTListDateM_MAX
}DTListDateM_Setting;

extern VControl DTListDateDCtrl;//List type 

typedef enum
{
DTListDateD_STRID_NULL,
DTListDateD_MAX
}DTListDateD_Setting;

extern VControl DTListTimeHCtrl;//List type 

typedef enum
{
DTListTimeH_STRID_NULL,
DTListTimeH_MAX
}DTListTimeH_Setting;

extern VControl DTListTimeMCtrl;//List type 

typedef enum
{
DTListTimeM_STRID_NULL,
DTListTimeM_MAX
}DTListTimeM_Setting;

extern VControl DTListTimeHRCtrl;//List type 

typedef enum
{
DTListTimeHR_STRID_NULL,
DTListTimeHR_STRID_NULL2,
DTListTimeHR_MAX
}DTListTimeHR_Setting;

extern VControl DTCursorCtrl;//Panel type 

extern VControl StaticArrwUCtrl;//Static type 

extern VControl StaticArrwDCtrl;//Static type 

extern VControl SymbolP1Ctrl;//Static type 

extern VControl SymbolP2Ctrl;//Static type 

extern VControl SymbolP3Ctrl;//Static type 

//---------------------MenuDatetimeCtrl User Export---------------------------
#endif
